<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>lesson-25 – LTC Dusty Turner</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../MA206-AY26-1/lesson-24.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-89a4c75c28f39d544352a2d30bce53fa.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">LTC Dusty Turner</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../index.html" aria-current="page"> 
<span class="menu-text">MA206-AY26-1</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../MA206-AY26-1/lesson-25.html">Lesson 25</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course Information</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lesson 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lesson 2</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lesson 3</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lesson 4</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lesson 5</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lesson 6</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lesson 7</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lesson 8</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lesson 9</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lesson 10</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lesson 11</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lesson 12</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lesson 13</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lesson 14</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-15.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lesson 15</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lesson 16</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lesson 17</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-18.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lesson 18</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-19.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lesson 19</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-20.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lesson 20</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-21.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lesson 21</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-22.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lesson 22</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-23.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lesson 23</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-24.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lesson 24</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../MA206-AY26-1/lesson-25.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Lesson 25</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#lesson-25---multiple-linear-regression-ii" id="toc-lesson-25---multiple-linear-regression-ii" class="nav-link active" data-scroll-target="#lesson-25---multiple-linear-regression-ii">Lesson 25 - Multiple Linear Regression II</a>
  <ul class="collapse">
  <li><a href="#lesson-administration" id="toc-lesson-administration" class="nav-link" data-scroll-target="#lesson-administration">Lesson Administration</a>
  <ul class="collapse">
  <li><a href="#calendar" id="toc-calendar" class="nav-link" data-scroll-target="#calendar">Calendar</a></li>
  <li><a href="#sil-2-points" id="toc-sil-2-points" class="nav-link" data-scroll-target="#sil-2-points">SIL 2 Points</a></li>
  <li><a href="#milestone-5" id="toc-milestone-5" class="nav-link" data-scroll-target="#milestone-5">Milestone 5</a></li>
  <li><a href="#exploration-exercise-4.4" id="toc-exploration-exercise-4.4" class="nav-link" data-scroll-target="#exploration-exercise-4.4">Exploration Exercise 4.4</a></li>
  <li><a href="#milestone-6-draft-tech-report" id="toc-milestone-6-draft-tech-report" class="nav-link" data-scroll-target="#milestone-6-draft-tech-report">Milestone 6: Draft Tech Report</a></li>
  <li><a href="#project-presentations" id="toc-project-presentations" class="nav-link" data-scroll-target="#project-presentations">Project Presentations</a></li>
  <li><a href="#milestone-7" id="toc-milestone-7" class="nav-link" data-scroll-target="#milestone-7">Milestone 7</a></li>
  <li><a href="#milestone-8" id="toc-milestone-8" class="nav-link" data-scroll-target="#milestone-8">Milestone 8</a></li>
  <li><a href="#tee-times" id="toc-tee-times" class="nav-link" data-scroll-target="#tee-times">TEE Times</a></li>
  </ul></li>
  <li><a href="#multiple-linear-regression" id="toc-multiple-linear-regression" class="nav-link" data-scroll-target="#multiple-linear-regression">Multiple Linear Regression</a>
  <ul class="collapse">
  <li><a href="#a-reminder" id="toc-a-reminder" class="nav-link" data-scroll-target="#a-reminder">A Reminder</a></li>
  </ul></li>
  <li><a href="#interactions" id="toc-interactions" class="nav-link" data-scroll-target="#interactions">Interactions</a>
  <ul class="collapse">
  <li><a href="#comparing-models" id="toc-comparing-models" class="nav-link" data-scroll-target="#comparing-models">Comparing Models</a></li>
  </ul></li>
  <li><a href="#validity-conditions" id="toc-validity-conditions" class="nav-link" data-scroll-target="#validity-conditions">Validity Conditions</a>
  <ul class="collapse">
  <li><a href="#linearity" id="toc-linearity" class="nav-link" data-scroll-target="#linearity">Linearity</a></li>
  <li><a href="#independence" id="toc-independence" class="nav-link" data-scroll-target="#independence">Independence</a></li>
  <li><a href="#normal-distribution" id="toc-normal-distribution" class="nav-link" data-scroll-target="#normal-distribution">Normal Distribution</a></li>
  <li><a href="#equal-variance" id="toc-equal-variance" class="nav-link" data-scroll-target="#equal-variance">Equal Variance</a></li>
  </ul></li>
  <li><a href="#adventure-one---example-of-what-to-do-for-milestone-5" id="toc-adventure-one---example-of-what-to-do-for-milestone-5" class="nav-link" data-scroll-target="#adventure-one---example-of-what-to-do-for-milestone-5">Adventure One - Example of what to do for Milestone 5</a></li>
  <li><a href="#in-class-exercise---adventure-two---will-revisit-lesson-26" id="toc-in-class-exercise---adventure-two---will-revisit-lesson-26" class="nav-link" data-scroll-target="#in-class-exercise---adventure-two---will-revisit-lesson-26">In Class Exercise - Adventure Two - Will revisit lesson 26</a></li>
  <li><a href="#partial-solution" id="toc-partial-solution" class="nav-link" data-scroll-target="#partial-solution">Partial Solution</a></li>
  <li><a href="#before-you-leave" id="toc-before-you-leave" class="nav-link" data-scroll-target="#before-you-leave">Before you leave</a>
  <ul class="collapse">
  <li><a href="#today" id="toc-today" class="nav-link" data-scroll-target="#today">Today:</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="lesson-25---multiple-linear-regression-ii" class="level1">
<h1>Lesson 25 - Multiple Linear Regression II</h1>
<!-- page-scoped CSS -->
<style>
/* compact list utility */
.compact ul, .compact ol { margin: 0.25rem 0 0.25rem 1.2rem; }
.compact li { margin: 0.1rem 0; }
.compact li p { margin: 0; }
</style>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lesson-25_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<section id="lesson-administration" class="level2">
<h2 class="anchored" data-anchor-id="lesson-administration">Lesson Administration</h2>
<section id="calendar" class="level3">
<h3 class="anchored" data-anchor-id="calendar">Calendar</h3>
<section id="day-1" class="level4">
<h4 class="anchored" data-anchor-id="day-1">Day 1</h4>
<p><img src="assets/img/lesson/lesson25day1.png" class="img-fluid"></p>
</section>
<section id="day-2" class="level4">
<h4 class="anchored" data-anchor-id="day-2">Day 2</h4>
<p><img src="assets/img/lesson/lesson25day2.png" class="img-fluid"></p>
<p><img src="assets/img/lesson/lesson-25.png" class="img-fluid"></p>
</section>
</section>
<section id="sil-2-points" class="level3">
<h3 class="anchored" data-anchor-id="sil-2-points">SIL 2 Points</h3>
</section>
<section id="milestone-5" class="level3">
<h3 class="anchored" data-anchor-id="milestone-5">Milestone 5</h3>
<ul>
<li>Lesson 25.5</li>
<li><strong>Change</strong>: 9 November 2359</li>
<li><a href="https://westpoint.instructure.com/courses/10295/files/3148756?wrap=1">Milestone 5 Instructions</a></li>
</ul>
</section>
<section id="exploration-exercise-4.4" class="level3">
<h3 class="anchored" data-anchor-id="exploration-exercise-4.4">Exploration Exercise 4.4</h3>
<ul>
<li>Lesson 26</li>
<li>12-13 November</li>
<li>Link: TBD</li>
</ul>
</section>
<section id="milestone-6-draft-tech-report" class="level3">
<h3 class="anchored" data-anchor-id="milestone-6-draft-tech-report">Milestone 6: Draft Tech Report</h3>
<ul>
<li>Lesson 26.5</li>
<li>17 November</li>
<li><a href="https://westpoint.instructure.com/courses/10295/files/3148757?wrap=1">Milestone 6 Instructions</a></li>
</ul>
</section>
<section id="project-presentations" class="level3">
<h3 class="anchored" data-anchor-id="project-presentations">Project Presentations</h3>
<ul>
<li><strong>Need to know who will not be here on presentation day because of CPRC</strong></li>
</ul>
</section>
<section id="milestone-7" class="level3">
<h3 class="anchored" data-anchor-id="milestone-7">Milestone 7</h3>
</section>
<section id="milestone-8" class="level3">
<h3 class="anchored" data-anchor-id="milestone-8">Milestone 8</h3>
</section>
<section id="tee-times" class="level3">
<h3 class="anchored" data-anchor-id="tee-times">TEE Times</h3>
<!-- ![](assets/img/tee-times.png){fig-align="center" width="50%"} -->
<table class="caption-top table">
<thead>
<tr class="header">
<th>Date</th>
<th>Start</th>
<th>End</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Wed, 17 Dec 2025</td>
<td>1300</td>
<td>1630</td>
</tr>
<tr class="even">
<td>Thu, 18 Dec 2025</td>
<td>0730</td>
<td>1100</td>
</tr>
</tbody>
</table>
<!-- #### DMath Frisbee PLAYOFFS!! -->
<!-- **Math 1 vs EECS** -->
<!-- :::{.callout-note collapse="true" title="Previously 6-0"} -->
<!-- <div style="text-align: center; font-size: 5em;"> -->
<!-- 7-0 -->
<!-- </div> -->
<!-- ::: -->
<!-- ![](assets/img/frisbee.png){fig-align="center" width="50%"} -->
<section id="dmath-basketball" class="level4">
<h4 class="anchored" data-anchor-id="dmath-basketball">DMath Basketball!!</h4>
<p><strong>Math 1 vs…</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="Previously 0-0">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Previously 0-0
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div style="text-align: center; font-size: 5em;">
<p>1-0</p>
</div>
</div>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="assets/img/basketball.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%"></p>
</figure>
</div>
</section>
<section id="cal" class="level4">
<h4 class="anchored" data-anchor-id="cal">Cal</h4>
<!-- ![](assets/img/cal/waco-trip/cal-2aco5.jpg){fig-align="center" width="75%"}   -->
<!-- <div style="display: flex; justify-content: center;"> -->
<!--   <video style="max-width: 100%; height: auto; transform: rotate(180deg);" controls> -->
<!--     <source src="assets/video/cal-bunt-marad.mp4" type="video/mp4"> -->
<!--     Your browser does not support the video tag. -->
<!--   </video> -->
<!-- </div> -->
</section>
<section id="reese" class="level4">
<h4 class="anchored" data-anchor-id="reese">Reese</h4>
<!-- ![](assets/img/reese/reese-venom-4/rv3.PNG){fig-align="center" width="75%"}   -->
<!-- <div style="display: flex; justify-content: center;"> -->
<!--   <video style="max-width: 100%; height: auto;" controls> -->
<!-- <video style="max-width: 100%; height: auto; transform: rotate(180deg);" controls> -->
<!--     <source src="assets/video/reese-cage.mp4" type="video/mp4"> -->
<!--     Your browser does not support the video tag. -->
<!--   </video> -->
<!-- </div> -->
<!-- ![](assets/img/cal/cal-wilport.jpg){fig-align="center" width="75%"}   -->
<p>I got nothing… So enjoy these</p>
<center>
<iframe width="560" height="315" src="https://www.youtube.com/embed/Sd3xJ2L5aU8?si=LVnLPUkzEXNmIozU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen="">
</iframe>
</center>
<div style="display: flex; justify-content: center;">
<p><video style="max-width: 100%; height: auto;" controls=""> <source src="assets/video/waterballon.mp4" type="video/mp4"> Your browser does not support the video tag. </video></p>
</div>
</section>
</section>
</section>
<section id="multiple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="multiple-linear-regression">Multiple Linear Regression</h2>
<section id="a-reminder" class="level3">
<h3 class="anchored" data-anchor-id="a-reminder">A Reminder</h3>
<p>Remember this from last class?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> mpg <span class="sc">~</span> wt <span class="sc">+</span> <span class="fu">as.factor</span>(cyl), <span class="at">data =</span> mtcars)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ wt + as.factor(cyl), data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.5890 -1.2357 -0.5159  1.3845  5.7915 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      33.9908     1.8878  18.006  &lt; 2e-16 ***
wt               -3.2056     0.7539  -4.252 0.000213 ***
as.factor(cyl)6  -4.2556     1.3861  -3.070 0.004718 ** 
as.factor(cyl)8  -6.0709     1.6523  -3.674 0.000999 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.557 on 28 degrees of freedom
Multiple R-squared:  0.8374,    Adjusted R-squared:   0.82 
F-statistic: 48.08 on 3 and 28 DF,  p-value: 3.594e-11</code></pre>
</div>
</div>
<p>The fitted regression equation is:</p>
<p><span class="math display">\[
\widehat{mpg} = 33.99 - 3.21(\text{wt}) - 4.26(\text{cyl6}) - 6.07(\text{cyl8})
\]</span></p>
<p>To predict fuel efficiency for a <strong>3000-lb</strong>, <strong>6-cylinder</strong> car:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{mpg}
&amp;= 33.99 - 3.21(3.0) - 4.26(1) - 6.07(0) \\[6pt]
&amp;= 33.99 - 9.63 - 4.26 \\[6pt]
&amp;= 20.10
\end{aligned}
\]</span></p>
<p>So the model predicts:</p>
<p><span class="math display">\[
\boxed{\widehat{mpg} = 20.1}
\]</span></p>
</section>
</section>
<section id="interactions" class="level2">
<h2 class="anchored" data-anchor-id="interactions">Interactions</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> mpg <span class="sc">~</span> wt <span class="sc">+</span> <span class="fu">as.factor</span>(cyl) <span class="sc">+</span> hp <span class="sc">+</span> hp<span class="sc">:</span><span class="fu">as.factor</span>(cyl), <span class="at">data =</span> mtcars)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ wt + as.factor(cyl) + hp + hp:as.factor(cyl), 
    data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.1864 -1.4098 -0.4022  1.0186  4.3920 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         41.87732    3.23293  12.953 1.37e-12 ***
wt                  -3.05994    0.68275  -4.482 0.000143 ***
as.factor(cyl)6     -9.98213    5.76950  -1.730 0.095931 .  
as.factor(cyl)8    -11.72793    4.22507  -2.776 0.010276 *  
hp                  -0.09947    0.03487  -2.853 0.008576 ** 
as.factor(cyl)6:hp   0.07809    0.05236   1.492 0.148335    
as.factor(cyl)8:hp   0.08602    0.03703   2.323 0.028601 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.3 on 25 degrees of freedom
Multiple R-squared:  0.8826,    Adjusted R-squared:  0.8544 
F-statistic: 31.32 on 6 and 25 DF,  p-value: 1.831e-10</code></pre>
</div>
</div>
<p>We can write the fitted model as</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{mpg}
&amp;= 41.877
- 3.060\,(\text{wt})
- 9.982\,(\text{cyl6})
- 11.728\,(\text{cyl8}) - 0.09947\,(\text{hp})
+ 0.07809\,(\text{hp}\times \text{cyl6})
+ 0.08602\,(\text{hp}\times \text{cyl8})
\end{aligned}
\]</span></p>
<section id="comparing-models" class="level3">
<h3 class="anchored" data-anchor-id="comparing-models">Comparing Models</h3>
<p>Which one is better?</p>
<p>Lets turn to <span class="math inline">\(R^2\)</span></p>
<p>Model 1: .8374</p>
<p>Model 2: .8826</p>
</section>
</section>
<section id="validity-conditions" class="level2">
<h2 class="anchored" data-anchor-id="validity-conditions">Validity Conditions</h2>
<p><strong>Linearity</strong> — the relationship between predictors and the response is roughly linear<br>
<strong>Independence</strong> — observations are independent of each other<br>
<strong>Normal Distribution</strong> — residuals are approximately normal<br>
<strong>Equal Variance</strong> — variability of residuals is consistent across fitted values</p>
<section id="linearity" class="level3">
<h3 class="anchored" data-anchor-id="linearity">Linearity</h3>
<p>Check whether the relationship between predictors and the response is roughly linear.</p>
<p>Use a residuals vs fitted plot — you want to see a random scatter (no pattern).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod1, <span class="at">which =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lesson-25_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="independence" class="level3">
<h3 class="anchored" data-anchor-id="independence">Independence</h3>
<p>We can’t test this from the model alone — it depends on <strong>how the data were collected</strong>.<br>
You must verify that each observation is independent (e.g., different cars, people, or trials).</p>
</section>
<section id="normal-distribution" class="level3">
<h3 class="anchored" data-anchor-id="normal-distribution">Normal Distribution</h3>
<p>Check whether residuals are approximately normally distributed using a Q-Q plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod1, <span class="at">which =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lesson-25_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="equal-variance" class="level3">
<h3 class="anchored" data-anchor-id="equal-variance">Equal Variance</h3>
<p>Check for constant variance (homoscedasticity) — residuals should have similar spread across fitted values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod1, <span class="at">which =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lesson-25_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="adventure-one---example-of-what-to-do-for-milestone-5" class="level2">
<h2 class="anchored" data-anchor-id="adventure-one---example-of-what-to-do-for-milestone-5">Adventure One - Example of what to do for Milestone 5</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"diamonds"</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>diamonds <span class="sc">|&gt;</span> </span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample_n</span>(<span class="at">size =</span> <span class="dv">1000</span>) <span class="sc">|&gt;</span> </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span><span class="fu">c</span>(cut, clarity, price, color)) <span class="sc">|&gt;</span> </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> value, <span class="at">y =</span> price, <span class="at">colour =</span> color)) <span class="sc">+</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>name, <span class="at">scales =</span> <span class="st">"free"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lesson-25_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> price <span class="sc">~</span> carat <span class="sc">+</span> depth <span class="sc">+</span> table <span class="sc">+</span> x <span class="sc">+</span> y <span class="sc">+</span> z <span class="sc">+</span> cut <span class="sc">+</span> color <span class="sc">+</span> clarity, <span class="at">data =</span> diamonds)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = price ~ carat + depth + table + x + y + z + cut + 
    color + clarity, data = diamonds)

Residuals:
     Min       1Q   Median       3Q      Max 
-21376.0   -592.4   -183.5    376.4  10694.2 

Coefficients:
             Estimate Std. Error  t value Pr(&gt;|t|)    
(Intercept)  5753.762    396.630   14.507  &lt; 2e-16 ***
carat       11256.978     48.628  231.494  &lt; 2e-16 ***
depth         -63.806      4.535  -14.071  &lt; 2e-16 ***
table         -26.474      2.912   -9.092  &lt; 2e-16 ***
x           -1008.261     32.898  -30.648  &lt; 2e-16 ***
y               9.609     19.333    0.497  0.61918    
z             -50.119     33.486   -1.497  0.13448    
cut.L         584.457     22.478   26.001  &lt; 2e-16 ***
cut.Q        -301.908     17.994  -16.778  &lt; 2e-16 ***
cut.C         148.035     15.483    9.561  &lt; 2e-16 ***
cut^4         -20.794     12.377   -1.680  0.09294 .  
color.L     -1952.160     17.342 -112.570  &lt; 2e-16 ***
color.Q      -672.054     15.777  -42.597  &lt; 2e-16 ***
color.C      -165.283     14.725  -11.225  &lt; 2e-16 ***
color^4        38.195     13.527    2.824  0.00475 ** 
color^5       -95.793     12.776   -7.498 6.59e-14 ***
color^6       -48.466     11.614   -4.173 3.01e-05 ***
clarity.L    4097.431     30.259  135.414  &lt; 2e-16 ***
clarity.Q   -1925.004     28.227  -68.197  &lt; 2e-16 ***
clarity.C     982.205     24.152   40.668  &lt; 2e-16 ***
clarity^4    -364.918     19.285  -18.922  &lt; 2e-16 ***
clarity^5     233.563     15.752   14.828  &lt; 2e-16 ***
clarity^6       6.883     13.715    0.502  0.61575    
clarity^7      90.640     12.103    7.489 7.06e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1130 on 53916 degrees of freedom
Multiple R-squared:  0.9198,    Adjusted R-squared:  0.9198 
F-statistic: 2.688e+04 on 23 and 53916 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> price <span class="sc">~</span> carat <span class="sc">+</span> depth <span class="sc">+</span> table <span class="sc">+</span> x <span class="sc">+</span> z <span class="sc">+</span> cut <span class="sc">+</span> color <span class="sc">+</span> clarity, <span class="at">data =</span> diamonds)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = price ~ carat + depth + table + x + z + cut + color + 
    clarity, data = diamonds)

Residuals:
     Min       1Q   Median       3Q      Max 
-21378.8   -592.5   -183.5    376.3  10694.1 

Coefficients:
             Estimate Std. Error  t value Pr(&gt;|t|)    
(Intercept)  5768.782    395.474   14.587  &lt; 2e-16 ***
carat       11257.752     48.602  231.630  &lt; 2e-16 ***
depth         -64.003      4.517  -14.168  &lt; 2e-16 ***
table         -26.501      2.911   -9.103  &lt; 2e-16 ***
x           -1000.354     28.795  -34.740  &lt; 2e-16 ***
z             -47.925     33.194   -1.444  0.14880    
cut.L         584.600     22.476   26.010  &lt; 2e-16 ***
cut.Q        -302.211     17.983  -16.805  &lt; 2e-16 ***
cut.C         148.446     15.461    9.601  &lt; 2e-16 ***
cut^4         -20.619     12.371   -1.667  0.09559 .  
color.L     -1952.179     17.342 -112.572  &lt; 2e-16 ***
color.Q      -672.075     15.777  -42.599  &lt; 2e-16 ***
color.C      -165.277     14.725  -11.224  &lt; 2e-16 ***
color^4        38.193     13.526    2.824  0.00475 ** 
color^5       -95.780     12.776   -7.497 6.64e-14 ***
color^6       -48.452     11.614   -4.172 3.02e-05 ***
clarity.L    4097.613     30.256  135.431  &lt; 2e-16 ***
clarity.Q   -1925.133     28.226  -68.205  &lt; 2e-16 ***
clarity.C     982.322     24.150   40.676  &lt; 2e-16 ***
clarity^4    -364.976     19.285  -18.926  &lt; 2e-16 ***
clarity^5     233.635     15.751   14.833  &lt; 2e-16 ***
clarity^6       6.871     13.715    0.501  0.61640    
clarity^7      90.622     12.103    7.487 7.13e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1130 on 53917 degrees of freedom
Multiple R-squared:  0.9198,    Adjusted R-squared:  0.9198 
F-statistic: 2.81e+04 on 22 and 53917 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Candidate model</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> price <span class="sc">~</span> carat <span class="sc">+</span> depth <span class="sc">+</span> table <span class="sc">+</span> x <span class="sc">+</span> cut <span class="sc">+</span> color <span class="sc">+</span> clarity, <span class="at">data =</span> diamonds)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = price ~ carat + depth + table + x + cut + color + 
    clarity, data = diamonds)

Residuals:
     Min       1Q   Median       3Q      Max 
-21385.0   -592.4   -183.7    376.5  10694.6 

Coefficients:
             Estimate Std. Error  t value Pr(&gt;|t|)    
(Intercept)  5935.107    378.328   15.688  &lt; 2e-16 ***
carat       11256.968     48.600  231.626  &lt; 2e-16 ***
depth         -66.769      4.091  -16.322  &lt; 2e-16 ***
table         -26.457      2.911   -9.089  &lt; 2e-16 ***
x           -1029.478     20.549  -50.098  &lt; 2e-16 ***
cut.L         584.717     22.476   26.015  &lt; 2e-16 ***
cut.Q        -302.037     17.983  -16.795  &lt; 2e-16 ***
cut.C         148.065     15.459    9.578  &lt; 2e-16 ***
cut^4         -21.253     12.364   -1.719  0.08562 .  
color.L     -1952.128     17.342 -112.568  &lt; 2e-16 ***
color.Q      -672.207     15.777  -42.608  &lt; 2e-16 ***
color.C      -165.451     14.724  -11.236  &lt; 2e-16 ***
color^4        38.261     13.526    2.829  0.00468 ** 
color^5       -95.816     12.776   -7.500 6.50e-14 ***
color^6       -48.441     11.614   -4.171 3.04e-05 ***
clarity.L    4096.912     30.253  135.423  &lt; 2e-16 ***
clarity.Q   -1924.681     28.224  -68.192  &lt; 2e-16 ***
clarity.C     982.004     24.149   40.664  &lt; 2e-16 ***
clarity^4    -364.870     19.285  -18.920  &lt; 2e-16 ***
clarity^5     233.449     15.751   14.822  &lt; 2e-16 ***
clarity^6       6.973     13.715    0.508  0.61114    
clarity^7      90.738     12.103    7.497 6.63e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1130 on 53918 degrees of freedom
Multiple R-squared:  0.9198,    Adjusted R-squared:  0.9198 
F-statistic: 2.944e+04 on 21 and 53918 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>diamonds <span class="sc">|&gt;</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(cut, color, clarity)) <span class="sc">|&gt;</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sample_n</span>(<span class="dv">1000</span>) <span class="sc">|&gt;</span> </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairs</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lesson-25_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>mod4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> price <span class="sc">~</span> carat <span class="sc">+</span> depth <span class="sc">+</span> table <span class="sc">+</span> x <span class="sc">+</span> cut <span class="sc">+</span> color <span class="sc">+</span> clarity <span class="sc">+</span> carat<span class="sc">:</span>color, <span class="at">data =</span> diamonds)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = price ~ carat + depth + table + x + cut + color + 
    clarity + carat:color, data = diamonds)

Residuals:
     Min       1Q   Median       3Q      Max 
-16732.9   -513.8   -136.6    358.5  10550.5 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   10393.339    359.347  28.923  &lt; 2e-16 ***
carat         12646.011     49.034 257.900  &lt; 2e-16 ***
depth           -97.355      3.860 -25.223  &lt; 2e-16 ***
table           -28.297      2.735 -10.348  &lt; 2e-16 ***
x             -1624.864     20.623 -78.791  &lt; 2e-16 ***
cut.L           594.594     21.114  28.161  &lt; 2e-16 ***
cut.Q          -274.247     16.896 -16.232  &lt; 2e-16 ***
cut.C           132.434     14.523   9.119  &lt; 2e-16 ***
cut^4           -12.347     11.613  -1.063  0.28770    
color.L         329.781     34.252   9.628  &lt; 2e-16 ***
color.Q         513.842     31.643  16.239  &lt; 2e-16 ***
color.C        -119.817     29.087  -4.119 3.81e-05 ***
color^4          69.759     26.171   2.665  0.00769 ** 
color^5         250.440     24.647  10.161  &lt; 2e-16 ***
color^6         125.580     22.195   5.658 1.54e-08 ***
clarity.L      4113.880     28.459 144.556  &lt; 2e-16 ***
clarity.Q     -1981.152     26.554 -74.607  &lt; 2e-16 ***
clarity.C       991.093     22.698  43.665  &lt; 2e-16 ***
clarity^4      -353.021     18.117 -19.485  &lt; 2e-16 ***
clarity^5       208.673     14.801  14.099  &lt; 2e-16 ***
clarity^6        26.858     12.884   2.085  0.03711 *  
clarity^7       107.303     11.372   9.436  &lt; 2e-16 ***
carat:color.L -2454.649     34.150 -71.878  &lt; 2e-16 ***
carat:color.Q -1020.521     31.031 -32.887  &lt; 2e-16 ***
carat:color.C   212.081     29.261   7.248 4.29e-13 ***
carat:color^4    19.164     27.152   0.706  0.48031    
carat:color^5  -396.193     26.071 -15.196  &lt; 2e-16 ***
carat:color^6  -192.062     24.204  -7.935 2.14e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1061 on 53912 degrees of freedom
Multiple R-squared:  0.9293,    Adjusted R-squared:  0.9292 
F-statistic: 2.623e+04 on 27 and 53912 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Candidate model</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>mod5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> price <span class="sc">~</span> carat <span class="sc">+</span> depth <span class="sc">+</span> table <span class="sc">+</span> x <span class="sc">+</span> cut <span class="sc">+</span> color <span class="sc">+</span> clarity <span class="sc">+</span> carat<span class="sc">:</span>color <span class="sc">+</span> clarity<span class="sc">:</span>carat, <span class="at">data =</span> diamonds)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = price ~ carat + depth + table + x + cut + color + 
    clarity + carat:color + clarity:carat, data = diamonds)

Residuals:
     Min       1Q   Median       3Q      Max 
-22707.3   -301.6     -0.9    271.9   8784.4 

Coefficients:
                 Estimate Std. Error  t value Pr(&gt;|t|)    
(Intercept)     21244.877    290.112   73.230  &lt; 2e-16 ***
carat           16453.723     45.710  359.960  &lt; 2e-16 ***
depth            -163.331      3.068  -53.232  &lt; 2e-16 ***
table             -39.541      2.158  -18.324  &lt; 2e-16 ***
x               -3095.798     18.360 -168.620  &lt; 2e-16 ***
cut.L             514.155     16.659   30.863  &lt; 2e-16 ***
cut.Q            -163.316     13.343  -12.239  &lt; 2e-16 ***
cut.C              71.287     11.459    6.221 4.98e-10 ***
cut^4               7.700      9.160    0.841  0.40059    
color.L           667.031     27.200   24.523  &lt; 2e-16 ***
color.Q           367.411     25.005   14.694  &lt; 2e-16 ***
color.C            15.497     22.987    0.674  0.50022    
color^4           104.494     20.654    5.059 4.22e-07 ***
color^5           200.370     19.445   10.305  &lt; 2e-16 ***
color^6            24.333     17.523    1.389  0.16495    
clarity.L       -3011.134     48.745  -61.774  &lt; 2e-16 ***
clarity.Q        1767.264     44.991   39.280  &lt; 2e-16 ***
clarity.C       -1411.691     37.984  -37.166  &lt; 2e-16 ***
clarity^4         863.630     30.089   28.703  &lt; 2e-16 ***
clarity^5        -454.165     24.029  -18.901  &lt; 2e-16 ***
clarity^6         112.514     20.512    5.485 4.15e-08 ***
clarity^7         -91.019     17.879   -5.091 3.58e-07 ***
carat:color.L   -2936.145     27.224 -107.853  &lt; 2e-16 ***
carat:color.Q    -861.382     24.531  -35.114  &lt; 2e-16 ***
carat:color.C      33.212     23.141    1.435  0.15124    
carat:color^4     -64.953     21.442   -3.029  0.00245 ** 
carat:color^5    -293.108     20.575  -14.246  &lt; 2e-16 ***
carat:color^6     -24.459     19.136   -1.278  0.20119    
carat:clarity.L  7881.781     51.240  153.820  &lt; 2e-16 ***
carat:clarity.Q -2165.582     45.783  -47.301  &lt; 2e-16 ***
carat:clarity.C  1714.611     41.112   41.706  &lt; 2e-16 ***
carat:clarity^4  -945.245     36.053  -26.218  &lt; 2e-16 ***
carat:clarity^5   488.264     31.404   15.548  &lt; 2e-16 ***
carat:clarity^6    28.838     27.156    1.062  0.28827    
carat:clarity^7   279.667     21.976   12.726  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 837 on 53905 degrees of freedom
Multiple R-squared:  0.956, Adjusted R-squared:  0.956 
F-statistic: 3.445e+04 on 34 and 53905 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Linear</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod5, <span class="at">which =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lesson-25_files/figure-html/unnamed-chunk-9-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Inedpendence</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># N </span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod5, <span class="at">which =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lesson-25_files/figure-html/unnamed-chunk-9-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#E </span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod5, <span class="at">which =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lesson-25_files/figure-html/unnamed-chunk-9-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="in-class-exercise---adventure-two---will-revisit-lesson-26" class="level2">
<h2 class="anchored" data-anchor-id="in-class-exercise---adventure-two---will-revisit-lesson-26">In Class Exercise - Adventure Two - Will revisit lesson 26</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>diamonds</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 53,940 × 10
   carat cut       color clarity depth table price     x     y     z
   &lt;dbl&gt; &lt;ord&gt;     &lt;ord&gt; &lt;ord&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1  0.23 Ideal     E     SI2      61.5    55   326  3.95  3.98  2.43
 2  0.21 Premium   E     SI1      59.8    61   326  3.89  3.84  2.31
 3  0.23 Good      E     VS1      56.9    65   327  4.05  4.07  2.31
 4  0.29 Premium   I     VS2      62.4    58   334  4.2   4.23  2.63
 5  0.31 Good      J     SI2      63.3    58   335  4.34  4.35  2.75
 6  0.24 Very Good J     VVS2     62.8    57   336  3.94  3.96  2.48
 7  0.24 Very Good I     VVS1     62.3    57   336  3.95  3.98  2.47
 8  0.26 Very Good H     SI1      61.9    55   337  4.07  4.11  2.53
 9  0.22 Fair      E     VS2      65.1    61   337  3.87  3.78  2.49
10  0.23 Very Good H     VS1      59.4    61   338  4     4.05  2.39
# ℹ 53,930 more rows</code></pre>
</div>
</div>
<ol type="1">
<li><p>In addition to carat size, what other variables might be associated with the price of a diamond?</p></li>
<li><p>Create a comparative box plot of <code>price</code> (response variable on the y-axis) by <code>cut</code> (explanatory variable on the x-axis).<br>
Which cut category tends to have higher prices? Is this what you would expect?</p></li>
<li><p>Fit a simple linear model for <code>price</code> using <code>carat</code> as the explanatory variable and <code>price</code> as the response variable.<br>
</p></li>
</ol>
<ol type="a">
<li>Write out the regression equation with intercept, coefficients, and variable names.<br>
</li>
<li>Interpret the coefficient of <code>carat</code> in the context of this model.<br>
</li>
<li>What is the strength of evidence that <code>carat</code> is related to <code>price</code>?</li>
</ol>
<ol start="4" type="1">
<li><p>Create a scatterplot of <code>price</code> versus <code>carat</code>, colored by <code>cut</code>.<br>
Do higher-quality cuts tend to cluster at different price or carat ranges?<br>
How might this influence your interpretation of the relationship between carat and price?</p></li>
<li><p>Fit a multiple regression model for <code>price</code> using both <code>carat</code> and <code>cut</code> as explanatory variables.<br>
</p></li>
</ol>
<ol type="a">
<li>Write out the regression equation with intercept, coefficients, and variable names.<br>
</li>
<li>Interpret the coefficient for <code>cut</code> while controlling for <code>carat</code>.</li>
</ol>
<ol start="6" type="1">
<li><p>How much total variation in diamond price is explained by this model (i.e., (R^2))?</p></li>
<li><p>The model in #5 assumes that the effect of <code>carat</code> on <code>price</code> is the same across all cuts.<br>
How can we check whether this assumption is valid?</p></li>
<li><p>Fit a multiple regression model for <code>price</code> using both <code>carat</code> and <code>cut</code>, including an interaction between them.<br>
Write out the regression equation with intercept, coefficients, and variable names.</p></li>
<li><p>Among the <strong>Ideal</strong> cut diamonds, how much does price increase for a one-unit increase in carat?</p></li>
<li><p>Among the <strong>Fair</strong> cut diamonds, how much does price increase for a one-unit increase in carat?</p></li>
<li><p>Is the interaction between <code>carat</code> and <code>cut</code> statistically significant?<br>
State your null and alternative hypotheses for the interaction term and report the test statistic and p-value.</p></li>
<li><p>To what population are you willing to generalize your results?<br>
Can you draw a cause-and-effect conclusion about carat size and diamond price? Why or why not?</p></li>
</ol>
</section>
<section id="partial-solution" class="level2">
<h2 class="anchored" data-anchor-id="partial-solution">Partial Solution</h2>
<p>Ask a Research Question</p>
<ol type="1">
<li>In addition to carat size, what other variables might be associated with the price of a diamond?</li>
</ol>
<p>Design a Study and Explore the Data</p>
<p>The <code>diamonds</code> dataset in R contains information about 53,940 diamonds, including their price (in U.S. dollars), carat, cut, color, clarity, and several physical measurements (<code>x</code>, <code>y</code>, <code>z</code>, <code>depth</code>, <code>table</code>).</p>
<p>We’ll examine how carat size and quality characteristics relate to diamond price.</p>
<ol start="2" type="1">
<li>Use R to create a comparative box plot of <code>price</code> (Response Variable on the y-axis) by <code>cut</code> (Explanatory Variable on the x-axis).
<ul>
<li>Which cut category tends to have higher prices?<br>
</li>
<li>Is this what you would expect?</li>
</ul></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(diamonds, <span class="fu">aes</span>(<span class="at">x =</span> cut, <span class="at">y =</span> price)) <span class="sc">+</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Diamond Price by Cut Quality"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lesson-25_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="3" type="1">
<li>Create a simple linear model for <code>price</code> using <code>carat</code> as the Explanatory Variable and <code>price</code> as the Response Variable.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> carat, <span class="at">data =</span> diamonds)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = price ~ carat, data = diamonds)

Residuals:
     Min       1Q   Median       3Q      Max 
-18585.3   -804.8    -18.9    537.4  12731.7 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -2256.36      13.06  -172.8   &lt;2e-16 ***
carat        7756.43      14.07   551.4   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1549 on 53938 degrees of freedom
Multiple R-squared:  0.8493,    Adjusted R-squared:  0.8493 
F-statistic: 3.041e+05 on 1 and 53938 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ol type="a">
<li>Write out the simple linear regression equation with intercept, coefficients, and variable names.</li>
</ol>
<p><span class="math display">\[
\widehat{price} = b_0 + b_1(\text{carat})
\]</span></p>
<ol start="2" type="a">
<li>Interpret the coefficient of carat in the context of this model.<br>
</li>
<li>Based on the p-value for the slope, what is the strength of evidence that <code>carat</code> is related to <code>price</code>?</li>
</ol>
<ol start="4" type="1">
<li>Generate a scatterplot of <code>price</code> (y-axis) versus <code>carat</code> (x-axis), colored by <code>cut</code>.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(diamonds, <span class="fu">aes</span>(<span class="at">x =</span> carat, <span class="at">y =</span> price, <span class="at">color =</span> cut)) <span class="sc">+</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Diamond Price vs. Carat, by Cut"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lesson-25_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Do higher-quality cuts tend to cluster at different price or carat ranges?<br>
</li>
<li>How might this influence your interpretation of the relationship between carat and price?</li>
</ul>
<ol start="5" type="1">
<li>Fit a multiple regression model for <code>price</code> using both <code>carat</code> and <code>cut</code> as Explanatory Variables.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> carat <span class="sc">+</span> cut, <span class="at">data =</span> diamonds)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = price ~ carat + cut, data = diamonds)

Residuals:
     Min       1Q   Median       3Q      Max 
-17540.7   -791.6    -37.6    522.1  12721.4 

Coefficients:
            Estimate Std. Error  t value Pr(&gt;|t|)    
(Intercept) -2701.38      15.43 -175.061  &lt; 2e-16 ***
carat        7871.08      13.98  563.040  &lt; 2e-16 ***
cut.L        1239.80      26.10   47.502  &lt; 2e-16 ***
cut.Q        -528.60      23.13  -22.851  &lt; 2e-16 ***
cut.C         367.91      20.21   18.201  &lt; 2e-16 ***
cut^4          74.59      16.24    4.593 4.37e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1511 on 53934 degrees of freedom
Multiple R-squared:  0.8565,    Adjusted R-squared:  0.8565 
F-statistic: 6.437e+04 on 5 and 53934 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ol type="a">
<li>Write out the multiple regression equation with intercept, coefficients, and variable names.<br>
</li>
<li>Interpret the coefficient for <code>cut</code> while controlling for <code>carat</code>.</li>
</ol>
<ol start="6" type="1">
<li><p>How much total variation in diamond price is explained by this model (i.e., (R^2))?</p></li>
<li><p>This model assumes that the effect of carat on price is the same across all cuts.</p>
<ul>
<li>How can we check whether this assumption is valid?</li>
</ul></li>
<li><p>Create a multiple regression model for <code>price</code> using both <code>carat</code> and <code>cut</code>, <strong>including an interaction</strong> between them.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> carat <span class="sc">*</span> cut, <span class="at">data =</span> diamonds)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = price ~ carat * cut, data = diamonds)

Residuals:
     Min       1Q   Median       3Q      Max 
-14878.3   -793.0    -23.0    546.3  12706.2 

Coefficients:
            Estimate Std. Error  t value Pr(&gt;|t|)    
(Intercept) -2271.95      20.94 -108.513  &lt; 2e-16 ***
carat        7468.05      19.49  383.200  &lt; 2e-16 ***
cut.L        -278.21      57.17   -4.866 1.14e-06 ***
cut.Q         363.22      50.51    7.191 6.50e-13 ***
cut.C        -172.96      42.81   -4.041 5.34e-05 ***
cut^4          67.55      33.40    2.022   0.0431 *  
carat:cut.L  1538.10      50.96   30.183  &lt; 2e-16 ***
carat:cut.Q  -781.89      45.89  -17.037  &lt; 2e-16 ***
carat:cut.C   509.65      41.36   12.321  &lt; 2e-16 ***
carat:cut^4    69.70      34.38    2.027   0.0426 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1498 on 53930 degrees of freedom
Multiple R-squared:  0.8591,    Adjusted R-squared:  0.859 
F-statistic: 3.653e+04 on 9 and 53930 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Write out the regression equation with intercept, coefficients, and variable names.</p>
<p><span class="math display">\[
\widehat{price} = b_0 + b_1(\text{carat}) + b_2(\text{cut}) + b_3(\text{carat} \times \text{cut})
\]</span></p>
<ol start="9" type="1">
<li><p>Among the <strong>Ideal</strong> cut diamonds, how much does price increase for a one-unit increase in carat?</p></li>
<li><p>Among the <strong>Fair</strong> cut diamonds, how much does price increase for a one-unit increase in carat?</p></li>
<li><p>Is the interaction between <code>carat</code> and <code>cut</code> statistically significant?</p>
<ul>
<li>State your null and alternative hypotheses for the interaction term.<br>
</li>
<li>Report the test statistic and p-value.</li>
</ul></li>
<li><p>To what population are you willing to generalize your results?</p>
<ul>
<li>Can you draw a cause-and-effect conclusion about carat size and diamond price?<br>
</li>
<li>Why or why not?</li>
</ul></li>
<li><p>Check each of the four <strong>Validity Conditions</strong> for the multiple regression you ran in #8.</p>
<ul>
<li>Include all three validity plots for your regression model.<br>
</li>
<li>Justify each of the four conditions: Linearity, Independence, Normality, and Equal Variance.</li>
</ul></li>
</ol>
<section id="linearity-1" class="level4">
<h4 class="anchored" data-anchor-id="linearity-1">Linearity</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod3, <span class="at">which =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lesson-25_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="independence-1" class="level4">
<h4 class="anchored" data-anchor-id="independence-1">Independence</h4>
<p>Must be justified based on data collection (not tested statistically).</p>
</section>
<section id="normal-distribution-1" class="level4">
<h4 class="anchored" data-anchor-id="normal-distribution-1">Normal Distribution</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod3, <span class="at">which =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lesson-25_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="equal-variance-1" class="level4">
<h4 class="anchored" data-anchor-id="equal-variance-1">Equal Variance</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod3, <span class="at">which =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lesson-25_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="before-you-leave" class="level2">
<h2 class="anchored" data-anchor-id="before-you-leave">Before you leave</h2>
<section id="today" class="level3">
<h3 class="anchored" data-anchor-id="today">Today:</h3>
<ul>
<li>Any questions for me?</li>
</ul>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../MA206-AY26-1/lesson-24.html" class="pagination-link" aria-label="Lesson 24">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Lesson 24</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>