languageCode = "en"

[params]
  mainSections = ["post"]

[[menus.main]]
  name = "Blog"
  url = "/post/"
  weight = 10

[[menus.main]]
  name = "Tags"
  url = "/tags/"
  weight = 20

[[menus.main]]
  name = "CV"
  url = "/CV.pdf"
  weight = 30

[[menus.main]]
  name = "Search"
  identifier = "search"
  url = "/search/"
  weight = 40
