colorScheme = "congo"

[homepage]
  layout = "custom"
  showRecent = false

[author]
  name = "Dusty Turner"
  headline = "~ Data Science - Lightly Edited ~"
  image = "media/family_bug.png"
  bio = "Army Officer • Operations Research Systems Analyst • Statistician"

  [[author.links]]
    email = "mailto:dusty.s.turner@gmail.com"
  [[author.links]]
    github = "https://github.com/dusty-turner"
  [[author.links]]
    linkedin = "https://www.linkedin.com/in/dustysturner/"
  [[author.links]]
    twitter = "https://twitter.com/dtdusty"

[article]
  showDate = true
  showAuthor = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showComments = true
  showMath = true

[taxonomy]
  showTermCount = true

[search]
  provider = "fuse"

[comments]
  provider = "disqus"
