baseURL: 'https://www.dustysturner.com/'
languageCode: en
title: Dusty Turner
theme: hugo-nuo
enableRobotsTXT: yes
PygmentsCodeFences: yes
canonifyurls: yes
disqusShortname: disqus_shortname
googleAnalytics: UA-XXXXXXXX-X
copyright: © This post is licensed under a Creative Commons Attribution-NonCommercial
  4.0 International License，please give source if you wish to quote or reproduce.
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: works
      name: Works
      url: https://github.com/laozhu
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
params:
  author: Ritchie Zhu
  avatar: images/avatar.png
  bg: images/grey-prism.svg
  changyan: no
  changyanConf: prod_0908b1cb9a581501753cce1ed074dbe3
  changyanId: cyt3toRiB
  description: Hugo is one of the most popular open-source static site generators.
    With its amazing speed and flexibility, Hugo makes building websites fun again.
  email: name@domain.com
  github: github_username
  googleSiteVerification: _moDmnnBNVLBN1rzNxyGUGdPHE20YgbmrtzLIbxaWFc
  linkedin: linkedin_username
  msValidate: 22596E34341DD1D17D6022C44647E587
  paginate: 10
  seotitle: "Dusty Turner"
  subtitle: ~ Data Science - Lightly Edited ~
  twitter: dtdusty
  wechat: images/qrcode.jpg
  weibo: weibo_username

markup:
  goldmark:
    renderer:
      unsafe: true
