baseURL: 'https://www.dustysturner.com/'
languageCode: en
title: Dusty Turner
theme: hugo-nuo
enableRobotsTXT: yes
PygmentsCodeFences: yes
canonifyurls: yes
disqusShortname: dusty-turner
googleAnalytics: "UA-109926409-1"
copyright: © This post is licensed under a Creative Commons Attribution-NonCommercial
  4.0 International License，please give source if you wish to quote or reproduce.
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: github
      name: Github
      url: https://github.com/dusty-turner
      weight: 20
    - identifier: cv
      name: CV
      url: "/CV.pdf"
      weight: 30
    # - identifier: tags
    #   name: Tags
    #   url: /tags/
    #   weight: 90
params:
  author: Dusty Turner
  avatar: images/avatar.png
  bg: images/grey-prism.svg
#  changyan: no
#  changyanConf: prod_0908b1cb9a581501753cce1ed074dbe3
#  changyanId: cyt3toRiB
  description: Hugo is one of the most popular open-source static site generators.
    With its amazing speed and flexibility, Hugo makes building websites fun again.
  email: dusty.s.turner@gmail.com
  github: dusty-turner
  googleSiteVerification: "-jH0wqxQCDh6JrcCbL9tuGso_EV4u1BRT93XjGqNsfo"
  linkedin: dusty-turner-34a148112/
  #msValidate: 22596E34341DD1D17D6022C44647E587
  paginate: 10
  seotitle: "Dusty Turner"
  subtitle: ~ Data Science - Lightly Edited ~
  twitter: dtdusty
  #wechat: images/qrcode.jpg
  #weibo: weibo_username

markup:
  goldmark:
    renderer:
      unsafe: true
