<!doctype html>
<html
  lang="en"
  dir="ltr"
  class="scroll-smooth"
  data-default-appearance="light"
  data-auto-appearance="true"><head>
  <meta charset="utf-8">
  
    <meta http-equiv="content-language" content="en">
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta name="theme-color">

  
  
    <title>A Farewell Ode To My Old Grey Truck &middot; Dusty Turner</title>
    <meta name="title" content="A Farewell Ode To My Old Grey Truck &middot; Dusty Turner">
  

  
  
  
    <meta name="keywords" content="datascience,beatnavy,ford,">
  
  
  
  <link rel="canonical" href="https://www.dustysturner.com/post/a-farewell-ode-to-my-old-grey-truck/">
  

  
  
    <meta name="author" content="Dusty Turner">
  
  
    
      
        
      
    
      
        
          <link href="https://github.com/dusty-turner" rel="me">
        
      
    
      
        
          <link href="https://www.linkedin.com/in/dustysturner/" rel="me">
        
      
    
      
        
          <link href="https://twitter.com/dtdusty" rel="me">
        
      
    
  

  
  <meta property="og:url" content="https://www.dustysturner.com/post/a-farewell-ode-to-my-old-grey-truck/">
  <meta property="og:site_name" content="Dusty Turner">
  <meta property="og:title" content="A Farewell Ode To My Old Grey Truck">
  <meta property="og:description" content="A Tribute! Since the dawn of time, people have been developing human-like attachments to their transportation. I imagine Moses naming his chariot, Noah his ark, and maybe even Jesus naming his borrowed donkey.
Well, maybe I’m taking too much historical license, but man’s affinity for their transportation remains.
At the age of 21, my dad and I split the cost of a 2005 Ford F150. The odometer read ~24,000 miles and it set us back ~$20,000.">
  <meta property="og:locale" content="en">
  <meta property="og:type" content="article">
    <meta property="article:section" content="post">
    <meta property="article:published_time" content="2019-10-11T00:00:00+00:00">
    <meta property="article:modified_time" content="2019-10-11T00:00:00+00:00">
    <meta property="article:tag" content="Datascience">
    <meta property="article:tag" content="Beatnavy">
    <meta property="article:tag" content="Ford">

  
  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="A Farewell Ode To My Old Grey Truck">
  <meta name="twitter:description" content="A Tribute! Since the dawn of time, people have been developing human-like attachments to their transportation. I imagine Moses naming his chariot, Noah his ark, and maybe even Jesus naming his borrowed donkey.
Well, maybe I’m taking too much historical license, but man’s affinity for their transportation remains.
At the age of 21, my dad and I split the cost of a 2005 Ford F150. The odometer read ~24,000 miles and it set us back ~$20,000.">

  
  
  
  
    
      
    
  
    
      
    
  
    
      
    
  
  
    
  

  
  
  
  
  
  

  

  
  
  
  
  
  
  
  
    
  
  
  <link
    type="text/css"
    rel="stylesheet"
    href="/css/main.bundle.min.358eafeb947ccb4508f8f6039efd327b1620349dd7e9542616c84fedc882c48ddb1f3028c4d21e2d0f756f46601800d2dad45e220f464d97a40db90ec60a4133.css">

  
  
  <script
    type="text/javascript"
    src="/js/appearance.min.6f41174b3a05b680820fe08cadbfa5fb7a7ca347b76a0955cdc68b9d8aca1ce24f0547e138cea33bcc7904d551a90afcb1cc7f2d9fe8557075d501419046c08c.js"></script>
  
  
  
  
  
  
    
    <script src="/lib/zoom/zoom.min.umd.a527109b68c082a70f3697716dd72a9d5aa8b545cf800cecbbc7399f2ca6f6e0ce3e431f2062b48bbfa47c9ea42822714060bef309be073f49b9c0e30d318d7b.js"></script>
  

  
  
  
    
  
  
    
  
  
  
  
  
  
    
    <script
      defer
      type="text/javascript"
      id="script-bundle"
      src="/js/main.bundle.min.858f7f82734cfae08d59fcf8d0eb186f01706a84e2f7d20d39edfd7bc8bed6166e02d5c65ecce1de82b1ac52d1e01d77bd1a82d19186fdae5fe6e12d867fcf68.js"
      data-copy="Copy"
      data-copied="Copied"></script>
  

  
  
























  

  

  

  

  













  
  
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
  

  
  <script type="application/ld+json">
  [{
    "@context": "https://schema.org",
    "@type": "Article",
    "articleSection": "Posts",
    "name": "A Farewell Ode To My Old Grey Truck",
    "headline": "A Farewell Ode To My Old Grey Truck",
    
    "inLanguage": "en",
    "url" : "https://www.dustysturner.com/post/a-farewell-ode-to-my-old-grey-truck/",
    "author" : {
      "@type": "Person",
      "name": "Dusty Turner"
    },
    "copyrightYear": "2019",
    "dateCreated": "2019-10-11T00:00:00\u002b00:00",
    "datePublished": "2019-10-11T00:00:00\u002b00:00",
    
    "dateModified": "2019-10-11T00:00:00\u002b00:00",
    
    "keywords": ["datascience","beatnavy","ford"],
    
    "mainEntityOfPage": "true",
    "wordCount": "2671"
  }]
  </script>



  
  
    

  <script
  async
  src="https://www.googletagmanager.com/gtag/js?id=G-PVH8CWDYYN"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-PVH8CWDYYN');
</script>





  

  
  
    <script>
(function() {
  var API_URL = "https://dustypi.tail280d22.ts.net/pageview/api/hit";

  function getVisitorId() {
    var match = document.cookie.match(/(?:^|; )_pvid=([^;]+)/);
    if (match) return match[1];
    var id = 'v_' + Math.random().toString(36).substr(2, 9) + Date.now().toString(36);
    document.cookie = "_pvid=" + id + "; path=/; max-age=31536000; SameSite=Lax";
    return id;
  }

  function sendHit(publicIp) {
    try {
      var data = {
        page: window.location.pathname,
        url: window.location.href,
        referrer: document.referrer || null,
        title: document.title || null,
        screen_width: screen.width,
        screen_height: screen.height,
        user_agent: navigator.userAgent,
        language: navigator.language,
        timestamp: new Date().toISOString(),
        visitor_id: getVisitorId(),
        timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || null,
        connection_type: (navigator.connection && navigator.connection.effectiveType) || null,
        public_ip: publicIp || null
      };

      if (navigator.sendBeacon) {
        navigator.sendBeacon(API_URL, JSON.stringify(data));
      } else {
        fetch(API_URL, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(data),
          keepalive: true
        }).catch(function() {});
      }
    } catch(e) {}
  }

  
  function getCachedIp() {
    try {
      var cached = JSON.parse(localStorage.getItem('_pvip') || '{}');
      if (cached.ip && cached.ts && (Date.now() - cached.ts) < 86400000) return cached.ip;
    } catch(e) {}
    return null;
  }

  function cacheIp(ip) {
    try { localStorage.setItem('_pvip', JSON.stringify({ ip: ip, ts: Date.now() })); } catch(e) {}
  }

  var cachedIp = getCachedIp();
  if (cachedIp) {
    sendHit(cachedIp);
    return;
  }

  
  var sent = false;
  var timer = setTimeout(function() { if (!sent) { sent = true; sendHit(null); } }, 3000);

  function tryService(url, extract) {
    fetch(url).then(function(r) { return r.json(); }).then(function(d) {
      var ip = extract(d);
      if (!sent && ip) { sent = true; clearTimeout(timer); cacheIp(ip); sendHit(ip); }
    }).catch(function() {});
  }

  tryService("https://api.ipify.org?format=json", function(d) { return d.ip; });
  tryService("https://api.seeip.org/jsonip", function(d) { return d.ip; });
})();
</script>

  

  
  

  
  
</head>


















  
  <body class="flex flex-col h-screen m-auto leading-7 max-w-7xl px-6 sm:px-14 md:px-24 lg:px-32 text-lg bg-neutral text-neutral-900 dark:bg-neutral-800 dark:text-neutral bf-scrollbar">
    <div id="the-top" class="absolute flex self-center">
      <a
        class="px-3 py-1 text-sm -translate-y-8 rounded-b-lg bg-primary-200 focus:translate-y-0 dark:bg-neutral-600"
        href="#main-content">
        <span class="font-bold text-primary-600 pe-2 dark:text-primary-400">&darr;</span>
        Skip to main content
      </a>
    </div>
    
    
      <div class="main-menu flex items-center w-full gap-2 p-1 pl-0">
  
  
    <a href="/" class="text-base font-medium truncate min-w-0 shrink">
      Dusty Turner
    </a>
  
  <div class="flex items-center ms-auto">
    <div class="hidden md:flex">
      <nav class="flex items-center gap-x-5 h-12">
  
    
      
  
    <a
      href="/post/"
      
      class="flex items-center bf-icon-color-hover"
      aria-label="Blog"
      title="">
      
      
        <span class="text-base font-medium break-normal">
          Blog
        </span>
      
    </a>
  

    
      
  
    <a
      href="/tags/"
      
      class="flex items-center bf-icon-color-hover"
      aria-label="Tags"
      title="">
      
      
        <span class="text-base font-medium break-normal">
          Tags
        </span>
      
    </a>
  

    
      
  
    <a
      href="/cv.pdf"
      
      class="flex items-center bf-icon-color-hover"
      aria-label="CV"
      title="">
      
      
        <span class="text-base font-medium break-normal">
          CV
        </span>
      
    </a>
  

    
      
  
    <a
      href="/search/"
      
      class="flex items-center bf-icon-color-hover"
      aria-label="Search"
      title="">
      
      
        <span class="text-base font-medium break-normal">
          Search
        </span>
      
    </a>
  

    
  

  

  

  
    <button
      id="search-button"
      aria-label="Search"
      class="text-base bf-icon-color-hover"
      title="Search (/)">
      <span class="relative block icon"><svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="search" class="svg-inline--fa fa-search fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"/></svg>
</span>
    </button>
  

  
    <div class="flex items-center">
      <button
        id="appearance-switcher"
        aria-label="Dark mode switcher"
        type="button"
        class="text-base bf-icon-color-hover">
        <div class="flex items-center justify-center dark:hidden">
          <span class="relative block icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M32 256c0-123.8 100.3-224 223.8-224c11.36 0 29.7 1.668 40.9 3.746c9.616 1.777 11.75 14.63 3.279 19.44C245 86.5 211.2 144.6 211.2 207.8c0 109.7 99.71 193 208.3 172.3c9.561-1.805 16.28 9.324 10.11 16.95C387.9 448.6 324.8 480 255.8 480C132.1 480 32 379.6 32 256z"/></svg>
</span>
        </div>
        <div class="items-center justify-center hidden dark:flex">
          <span class="relative block icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M256 159.1c-53.02 0-95.1 42.98-95.1 95.1S202.1 351.1 256 351.1s95.1-42.98 95.1-95.1S309 159.1 256 159.1zM509.3 347L446.1 255.1l63.15-91.01c6.332-9.125 1.104-21.74-9.826-23.72l-109-19.7l-19.7-109c-1.975-10.93-14.59-16.16-23.72-9.824L256 65.89L164.1 2.736c-9.125-6.332-21.74-1.107-23.72 9.824L121.6 121.6L12.56 141.3C1.633 143.2-3.596 155.9 2.736 164.1L65.89 256l-63.15 91.01c-6.332 9.125-1.105 21.74 9.824 23.72l109 19.7l19.7 109c1.975 10.93 14.59 16.16 23.72 9.824L256 446.1l91.01 63.15c9.127 6.334 21.75 1.107 23.72-9.822l19.7-109l109-19.7C510.4 368.8 515.6 356.1 509.3 347zM256 383.1c-70.69 0-127.1-57.31-127.1-127.1c0-70.69 57.31-127.1 127.1-127.1s127.1 57.3 127.1 127.1C383.1 326.7 326.7 383.1 256 383.1z"/></svg>
</span>
        </div>
      </button>
    </div>
  
</nav>



    </div>
    <div class="flex md:hidden">
      <div class="flex items-center h-14 gap-4">
  
    <button
      id="search-button-mobile"
      aria-label="Search"
      class="flex items-center justify-center bf-icon-color-hover"
      title="Search (/)">
      <span class="relative block icon"><svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="search" class="svg-inline--fa fa-search fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"/></svg>
</span>
    </button>
  

  
    <button
      id="appearance-switcher-mobile"
      type="button"
      aria-label="Dark mode switcher"
      class="flex items-center justify-center text-neutral-900 hover:text-primary-600 dark:text-neutral-200 dark:hover:text-primary-400">
      <div class="dark:hidden">
        <span class="relative block icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M32 256c0-123.8 100.3-224 223.8-224c11.36 0 29.7 1.668 40.9 3.746c9.616 1.777 11.75 14.63 3.279 19.44C245 86.5 211.2 144.6 211.2 207.8c0 109.7 99.71 193 208.3 172.3c9.561-1.805 16.28 9.324 10.11 16.95C387.9 448.6 324.8 480 255.8 480C132.1 480 32 379.6 32 256z"/></svg>
</span>
      </div>
      <div class="hidden dark:block">
        <span class="relative block icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M256 159.1c-53.02 0-95.1 42.98-95.1 95.1S202.1 351.1 256 351.1s95.1-42.98 95.1-95.1S309 159.1 256 159.1zM509.3 347L446.1 255.1l63.15-91.01c6.332-9.125 1.104-21.74-9.826-23.72l-109-19.7l-19.7-109c-1.975-10.93-14.59-16.16-23.72-9.824L256 65.89L164.1 2.736c-9.125-6.332-21.74-1.107-23.72 9.824L121.6 121.6L12.56 141.3C1.633 143.2-3.596 155.9 2.736 164.1L65.89 256l-63.15 91.01c-6.332 9.125-1.105 21.74 9.824 23.72l109 19.7l19.7 109c1.975 10.93 14.59 16.16 23.72 9.824L256 446.1l91.01 63.15c9.127 6.334 21.75 1.107 23.72-9.822l19.7-109l109-19.7C510.4 368.8 515.6 356.1 509.3 347zM256 383.1c-70.69 0-127.1-57.31-127.1-127.1c0-70.69 57.31-127.1 127.1-127.1s127.1 57.3 127.1 127.1C383.1 326.7 326.7 383.1 256 383.1z"/></svg>
</span>
      </div>
    </button>
  

  
    <input type="checkbox" id="mobile-menu-toggle" autocomplete="off" class="hidden peer">
    <label for="mobile-menu-toggle" class="flex items-center justify-center cursor-pointer bf-icon-color-hover">
      <span class="relative block icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M0 96C0 78.33 14.33 64 32 64H416C433.7 64 448 78.33 448 96C448 113.7 433.7 128 416 128H32C14.33 128 0 113.7 0 96zM0 256C0 238.3 14.33 224 32 224H416C433.7 224 448 238.3 448 256C448 273.7 433.7 288 416 288H32C14.33 288 0 273.7 0 256zM416 448H32C14.33 448 0 433.7 0 416C0 398.3 14.33 384 32 384H416C433.7 384 448 398.3 448 416C448 433.7 433.7 448 416 448z"/></svg>
</span>
    </label>

    <div
      role="dialog"
      aria-modal="true"
      style="scrollbar-gutter: stable;"
      class="fixed inset-0 z-50 invisible overflow-y-auto px-6 py-20 opacity-0 transition-[opacity,visibility] duration-300 peer-checked:visible peer-checked:opacity-100 bg-neutral-50/97 dark:bg-neutral-900/99
      bf-scrollbar">
      <label
        for="mobile-menu-toggle"
        class="fixed end-8 top-5 flex items-center justify-center z-50 h-12 w-12 cursor-pointer select-none rounded-full bf-icon-color-hover border bf-border-color bf-border-color-hover bg-neutral-50 dark:bg-neutral-900">
        <span class="relative block icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><path fill="currentColor" d="M310.6 361.4c12.5 12.5 12.5 32.75 0 45.25C304.4 412.9 296.2 416 288 416s-16.38-3.125-22.62-9.375L160 301.3L54.63 406.6C48.38 412.9 40.19 416 32 416S15.63 412.9 9.375 406.6c-12.5-12.5-12.5-32.75 0-45.25l105.4-105.4L9.375 150.6c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0L160 210.8l105.4-105.4c12.5-12.5 32.75-12.5 45.25 0s12.5 32.75 0 45.25l-105.4 105.4L310.6 361.4z"/></svg>
</span>
      </label>
      <nav class="mx-auto max-w-md space-y-6">
        
  
    
    <div class="px-2">
      <a
        href="/post/"
        aria-label="Blog"
        
        class="flex items-center gap-4 group bf-icon-color-hover text-neutral-700 dark:text-neutral-200">
        
        <span title="" class="text-2xl font-bold tracking-tight">
          Blog
        </span>
        
      </a>

      
    </div>
  
    
    <div class="px-2">
      <a
        href="/tags/"
        aria-label="Tags"
        
        class="flex items-center gap-4 group bf-icon-color-hover text-neutral-700 dark:text-neutral-200">
        
        <span title="" class="text-2xl font-bold tracking-tight">
          Tags
        </span>
        
      </a>

      
    </div>
  
    
    <div class="px-2">
      <a
        href="/cv.pdf"
        aria-label="CV"
        
        class="flex items-center gap-4 group bf-icon-color-hover text-neutral-700 dark:text-neutral-200">
        
        <span title="" class="text-2xl font-bold tracking-tight">
          CV
        </span>
        
      </a>

      
    </div>
  
    
    <div class="px-2">
      <a
        href="/search/"
        aria-label="Search"
        
        class="flex items-center gap-4 group bf-icon-color-hover text-neutral-700 dark:text-neutral-200">
        
        <span title="" class="text-2xl font-bold tracking-tight">
          Search
        </span>
        
      </a>

      
    </div>
  

        
  

        
  

      </nav>
    </div>
  
</div>







    </div>
  </div>
</div>





    
    <div class="relative flex flex-col grow">
      <main id="main-content" class="grow">
        
  
  <article>
    
    

    
    <header id="single_header" class="mt-5 max-w-prose">
      
      <h1 class="mt-0 text-4xl font-extrabold text-neutral-900 dark:text-neutral">
        A Farewell Ode To My Old Grey Truck
      </h1>
      <div class="mt-1 mb-6 text-base text-neutral-500 dark:text-neutral-400 print:hidden">
        





  
  



  

  
  
  
    
  

  

  
    
  

  

  
    
  

  
    
  

  

  

  

  

  


  <div class="flex flex-row flex-wrap items-center">
    
    
      <time datetime="2019-10-11T00:00:00&#43;00:00">11 October 2019</time><span class="px-2 text-primary-500">&middot;</span><span>2671 words</span><span class="px-2 text-primary-500">&middot;</span><span title="Reading time">13 mins</span>
    

    
    
  </div>

  

  
  
    <div class="flex flex-row flex-wrap items-center">
      
        
          
            
              <a class="relative mt-[0.5rem] me-2" href="/tags/datascience/">
                <span class="flex cursor-pointer">
  <span
    class="rounded-md border border-primary-400 px-1 py-[1px] text-xs font-normal text-primary-700 dark:border-primary-600 dark:text-primary-400">
    Datascience
  </span>
</span>

              </a>
            
              <a class="relative mt-[0.5rem] me-2" href="/tags/beatnavy/">
                <span class="flex cursor-pointer">
  <span
    class="rounded-md border border-primary-400 px-1 py-[1px] text-xs font-normal text-primary-700 dark:border-primary-600 dark:text-primary-400">
    Beatnavy
  </span>
</span>

              </a>
            
              <a class="relative mt-[0.5rem] me-2" href="/tags/ford/">
                <span class="flex cursor-pointer">
  <span
    class="rounded-md border border-primary-400 px-1 py-[1px] text-xs font-normal text-primary-700 dark:border-primary-600 dark:text-primary-400">
    Ford
  </span>
</span>

              </a>
            
          
        
      
    </div>
  

  
  



      </div>
      
        
  
  
  
  
  
  

  

  
    
    
<div class="flex author">
  
    
    
      
    
    
      
      
      
        
        
        
      
      <img
        class="!mt-0 !mb-0 h-24 w-24 rounded-full me-4"
        width="96"
        height="96"
        alt="Dusty Turner"
        src="/media/family_bug_hu_b3df7dc6b22442b3.png"
        data-zoom-src="/media/family_bug_hu_5e1e9d0ccb13609e.png">
    
  
  <div class="place-self-center">
    
      <div class="text-[0.6rem] uppercase leading-3 text-neutral-500 dark:text-neutral-400">
        Author
      </div>
      <div class="font-semibold leading-6 text-neutral-800 dark:text-neutral-300">
        Dusty Turner
      </div>
    
    
      <div class="text-sm text-neutral-700 dark:text-neutral-400">Army Officer • Operations Research Systems Analyst • Statistician</div>
    
    <div class="text-2xl sm:text-lg">
  <div class="flex flex-wrap text-neutral-400 dark:text-neutral-500">
    
      
        <a
          class="px-1 hover:text-primary-700 dark:hover:text-primary-400"
          href="mailto:dusty.s.turner@gmail.com"
          target="_blank"
          aria-label="Email"
          title="Email"
          rel="me noopener noreferrer"
          ><span class="inline-block align-text-bottom"><span class="relative block icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M207.8 20.73c-93.45 18.32-168.7 93.66-187 187.1c-27.64 140.9 68.65 266.2 199.1 285.1c19.01 2.888 36.17-12.26 36.17-31.49l.0001-.6631c0-15.74-11.44-28.88-26.84-31.24c-84.35-12.98-149.2-86.13-149.2-174.2c0-102.9 88.61-185.5 193.4-175.4c91.54 8.869 158.6 91.25 158.6 183.2l0 16.16c0 22.09-17.94 40.05-40 40.05s-40.01-17.96-40.01-40.05v-120.1c0-8.847-7.161-16.02-16.01-16.02l-31.98 .0036c-7.299 0-13.2 4.992-15.12 11.68c-24.85-12.15-54.24-16.38-86.06-5.106c-38.75 13.73-68.12 48.91-73.72 89.64c-9.483 69.01 43.81 128 110.9 128c26.44 0 50.43-9.544 69.59-24.88c24 31.3 65.23 48.69 109.4 37.49C465.2 369.3 496 324.1 495.1 277.2V256.3C495.1 107.1 361.2-9.332 207.8 20.73zM239.1 304.3c-26.47 0-48-21.56-48-48.05s21.53-48.05 48-48.05s48 21.56 48 48.05S266.5 304.3 239.1 304.3z"/></svg>
</span></span></a
        >
      
    
      
        <a
          class="px-1 hover:text-primary-700 dark:hover:text-primary-400"
          href="https://github.com/dusty-turner"
          target="_blank"
          aria-label="Github"
          title="Github"
          rel="me noopener noreferrer"
          ><span class="inline-block align-text-bottom"><span class="relative block icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512"><path fill="currentColor" d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"/></svg>
</span></span></a
        >
      
    
      
        <a
          class="px-1 hover:text-primary-700 dark:hover:text-primary-400"
          href="https://www.linkedin.com/in/dustysturner/"
          target="_blank"
          aria-label="Linkedin"
          title="Linkedin"
          rel="me noopener noreferrer"
          ><span class="inline-block align-text-bottom"><span class="relative block icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M416 32H31.9C14.3 32 0 46.5 0 64.3v383.4C0 465.5 14.3 480 31.9 480H416c17.6 0 32-14.5 32-32.3V64.3c0-17.8-14.4-32.3-32-32.3zM135.4 416H69V202.2h66.5V416zm-33.2-243c-21.3 0-38.5-17.3-38.5-38.5S80.9 96 102.2 96c21.2 0 38.5 17.3 38.5 38.5 0 21.3-17.2 38.5-38.5 38.5zm282.1 243h-66.4V312c0-24.8-.5-56.7-34.5-56.7-34.6 0-39.9 27-39.9 54.9V416h-66.4V202.2h63.7v29.2h.9c8.9-16.8 30.6-34.5 62.9-34.5 67.2 0 79.7 44.3 79.7 101.9V416z"/></svg>
</span></span></a
        >
      
    
      
        <a
          class="px-1 hover:text-primary-700 dark:hover:text-primary-400"
          href="https://twitter.com/dtdusty"
          target="_blank"
          aria-label="Twitter"
          title="Twitter"
          rel="me noopener noreferrer"
          ><span class="inline-block align-text-bottom"><span class="relative block icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"/></svg>
</span></span></a
        >
      
    
  </div>

</div>
  </div>
</div>

  

  

  
    <div class="mb-5"></div>
  

      
    </header>

    
    <section class="flex flex-col max-w-full mt-0 prose dark:prose-invert lg:flex-row">
      
      
      
      
      


      <div class="min-w-0 min-h-0 max-w-fit">
        

        <div class="article-content max-w-prose mb-20">
          
<script src="https://www.dustysturner.com/post/a-farewell-ode-to-my-old-grey-truck/index_files/kePrint/kePrint.js"></script>
<link href="https://www.dustysturner.com/post/a-farewell-ode-to-my-old-grey-truck/index_files/lightable/lightable.css" rel="stylesheet" />
<script src="https://www.dustysturner.com/post/a-farewell-ode-to-my-old-grey-truck/index_files/htmlwidgets/htmlwidgets.js"></script>
<script src="https://www.dustysturner.com/post/a-farewell-ode-to-my-old-grey-truck/index_files/jquery/jquery.min.js"></script>
<link href="https://www.dustysturner.com/post/a-farewell-ode-to-my-old-grey-truck/index_files/datatables-css/datatables-crosstalk.css" rel="stylesheet" />
<script src="https://www.dustysturner.com/post/a-farewell-ode-to-my-old-grey-truck/index_files/datatables-binding/datatables.js"></script>
<link href="https://www.dustysturner.com/post/a-farewell-ode-to-my-old-grey-truck/index_files/dt-core/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="https://www.dustysturner.com/post/a-farewell-ode-to-my-old-grey-truck/index_files/dt-core/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="https://www.dustysturner.com/post/a-farewell-ode-to-my-old-grey-truck/index_files/dt-core/js/jquery.dataTables.min.js"></script>
<link href="https://www.dustysturner.com/post/a-farewell-ode-to-my-old-grey-truck/index_files/crosstalk/css/crosstalk.css" rel="stylesheet" />
<script src="https://www.dustysturner.com/post/a-farewell-ode-to-my-old-grey-truck/index_files/crosstalk/js/crosstalk.min.js"></script>


<div id="a-tribute" class="section level2">
<h2>A Tribute!</h2>
<p>Since the dawn of time, people have been developing human-like attachments to their transportation. I imagine Moses naming his chariot, Noah his ark, and maybe even Jesus naming his borrowed donkey.</p>
<p>Well, maybe I’m taking too much historical license, but man’s affinity for their transportation remains.</p>
<p>At the age of 21, my dad and I split the cost of a 2005 Ford F150. The odometer read ~24,000 miles and it set us back ~$20,000.</p>
<center>
<img src="images/oldpickupedit.jpg" alt="OldTruck" width="500">
<!-- ![](oldpickupedit.jpg) -->
</center>
<p>I’ve been with this truck for 14 years - longer than I’ve known my wife. Its been with me from Texas to New York to Georgia to Missouri to Hawaii to Missouri to New Mexico to Ohio to New York to Virginia. Tragically, on the drive from New York to Virginia, the engine developed a tremendous rattling noise and a violent shake. Unbeknownst to me, it developed an oil leak sometime in the summer of ’19 and the 70 mph roads were too much for it to handle. Just short of its 200,000th mile, I laid it to rests in Fairfax Station, Virginia. It lived long enough to meet its successor, Old Grey Truck II.</p>
<center>
<img src="images/newtruckedit.jpg" alt="NewTruck" width="400">
<!-- <img src="images/newtruckedit.jpg" alt="NewTruck" width="500" height="600"> -->
<!-- ![](newtruckedit.jpg) -->
</center>
<p>The following is a (tongue-in-cheek) R style ode to my old friend. Long live Old Grey!</p>
<!-- [imageofoldtruck.png] -->
</div>
<div id="data" class="section level2">
<h2>Data</h2>
<p>I’ll explore the following <a href="www.github.com/dusty-turner">data</a>. I made an earlier version of this blog post <a href="www.dusty-turner/netlify.com/oldpost">here</a> where I looked at some similar, but incomplete, analysis on this data.</p>
<p>I’ll use the following packages to load, manipulate, and view the data.</p>
<pre class="r"><code>library(tidyverse)
library(lubridate)
library(skimr)
library(kableExtra)</code></pre>
<p>Below, you’ll notice that the observational unit is each time I filled up the pick-up. The column headers are pretty self explanatory.</p>
<p>To be explicit, here is a description of the data:</p>
<ul>
<li><code>FillUpDate</code>: Date I filled up the pick up with gasoline.</li>
<li><code>TotalMiles</code>: Odometer reading when I filled up the tank.</li>
<li><code>TankMiles</code>: Trip odometer reading for the most recent tank of gas. Reset every ‘fill up.’</li>
<li><code>Gallons</code>: Gallons of gasoline put in the tank at time of fill up.</li>
<li><code>MPG</code>: Calculated miles per gallon on the previous tank of gas. <code>TankMikes/Gallons</code></li>
<li><code>FinishTankDate</code>: Date of previous fill up.</li>
<li><code>Location</code>: is the location that I lived at the time of filling up the tank.</li>
</ul>
<pre class="r"><code>head(truck)</code></pre>
<pre><code>## # A tibble: 6 x 7
##   FillUpDate TotalMiles TankMiles Gallons   MPG FinishTankDate Location  
##   &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;          &lt;chr&gt;     
## 1 17-Feb-06      24251       366     22.6  16.2 18-Feb-06      Texas     
## 2 18-Feb-06      24443.      192.    12.8  15.0 18-Feb-06      Texas     
## 3 18-Feb-06      24765       322.    16.5  19.5 27-Feb-06      Texas     
## 4 27-Feb-06      25156       391     24.9  15.7 10-Mar-06      Texas     
## 5 10-Mar-06      25431.      275.    15.8  17.4 11-Mar-06      New York 1
## 6 11-Mar-06      25548.      117.     7.5  15.6 11-Mar-06      New York 1</code></pre>
<p>Thanks to <code>readr</code>, most of the columns read in appropriately. However, it looks like we’ll need to make an adjustment so that the dates are the correct class. Thanks <code>lubridate</code>!</p>
<pre class="r"><code>truck = 
truck %&gt;%
  mutate(FillUpDate = dmy(FillUpDate),
         FinishTankDate = dmy(FinishTankDate))
head(truck)</code></pre>
<pre><code>## # A tibble: 6 x 7
##   FillUpDate TotalMiles TankMiles Gallons   MPG FinishTankDate Location  
##   &lt;date&gt;          &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;date&gt;         &lt;chr&gt;     
## 1 2006-02-17     24251       366     22.6  16.2 2006-02-18     Texas     
## 2 2006-02-18     24443.      192.    12.8  15.0 2006-02-18     Texas     
## 3 2006-02-18     24765       322.    16.5  19.5 2006-02-27     Texas     
## 4 2006-02-27     25156       391     24.9  15.7 2006-03-10     Texas     
## 5 2006-03-10     25431.      275.    15.8  17.4 2006-03-11     New York 1
## 6 2006-03-11     25548.      117.     7.5  15.6 2006-03-11     New York 1</code></pre>
<!-- Using the nifty `skim` function we can glean some other information about my history with ol grey. -->
<!-- ```{r, results='asis'} -->
<!-- skim(truck) %>% -->
<!--   skimr::kable(format = "latex") -->
<!-- # skimr:: (truck) -->
<!-- ``` -->
</div>
<div id="fun-descriptive-stats" class="section level2">
<h2>Fun Descriptive Stats</h2>
<p>There are a handful of ‘fun’ descriptive statistics from the data.</p>
<pre class="r"><code>summary(truck)</code></pre>
<pre><code>##    FillUpDate           TotalMiles       TankMiles        Gallons     
##  Min.   :2006-02-17   Min.   : 24251   Min.   : 79.4   Min.   : 6.06  
##  1st Qu.:2009-07-04   1st Qu.: 65499   1st Qu.:333.0   1st Qu.:22.61  
##  Median :2012-02-17   Median :110550   Median :414.2   Median :27.30  
##  Mean   :2011-12-13   Mean   :108423   Mean   :392.7   Mean   :25.59  
##  3rd Qu.:2014-03-05   3rd Qu.:148723   3rd Qu.:459.3   3rd Qu.:29.73  
##  Max.   :2019-07-19   Max.   :193497   Max.   :799.6   Max.   :39.40  
##                                                        NA&#39;s   :1      
##       MPG         FinishTankDate         Location        
##  Min.   : 8.394   Min.   :2006-02-18   Length:432        
##  1st Qu.:14.506   1st Qu.:2009-07-08   Class :character  
##  Median :15.597   Median :2012-02-21   Mode  :character  
##  Mean   :15.373   Mean   :2011-12-18                     
##  3rd Qu.:16.503   3rd Qu.:2014-03-08                     
##  Max.   :25.834   Max.   :2019-07-19                     
##  NA&#39;s   :1        NA&#39;s   :1</code></pre>
<ul>
<li><p>We see that I more or less owned the truck from Feb of 06 through July of 2019. I filled it up 433 times and drove it until it his 193,497 miles…. so close!</p></li>
<li><p>The average miles per gallon was 15.6 and I even attained 25ish one time. The least was 8.4. I likely was pulling my wife’s car on a trailer on that tank.</p></li>
<li><p>Looks like I usually drove about 333 miles on a tank. I put as few at ~80 and as much as 799. Must have been the time a buddy filled it up and didn’t tell me :).</p></li>
<li><p>While it only has a 34 gallon tank, the max gallons added to the truck was 39.4. This is likely due to times when friends borrowed the truck and put in a few gallons for me and didn’t note it in my log. I compensated for it by adding it to the next fill up.</p></li>
</ul>
<p>How many times did this happen?</p>
<pre class="r"><code>truck %&gt;%
  select(Gallons) %&gt;%
  filter(Gallons&gt;34) </code></pre>
<pre><code>## # A tibble: 5 x 1
##   Gallons
##     &lt;dbl&gt;
## 1    39.4
## 2    34.2
## 3    34.4
## 4    34.2
## 5    34.6</code></pre>
<p>Lets look at the spread of the data a little closer to get a feel for the distribution of gallons per fill up, miles per gallon, and miles per tank of gas.</p>
<pre class="r"><code>truck %&gt;%
  gather(Measurement, Value, -FillUpDate, -FinishTankDate, -Location) %&gt;%
  filter(Measurement != &quot;TotalMiles&quot;) %&gt;%
  ggplot(aes(x=Value)) +
  geom_histogram() +
  facet_wrap(~Measurement, scales = &quot;free_x&quot;) +
  labs(x=&quot;&quot;, y = &quot;Number of Occurances (Fill Ups)&quot;, title = &quot;Frequency of Occurrence for Each Fill Up&quot;)</code></pre>
<p><img src="https://www.dustysturner.com/post/a-farewell-ode-to-my-old-grey-truck/index_files/figure-html/unnamed-chunk-7-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>It looks like gallons and miles per tank of gas (unsurprisingly) are right skewed as factors have a cap on the upper end (with a few exceptions when friends fill up and don’t tell me). Miles per gallon looks more normally distributed with a few more occurrences of fewer miles per gallon.</p>
<div id="fun-stratified-stats" class="section level3">
<h3>Fun Stratified Stats</h3>
<p>Lets see how well my truck performed in each location.</p>
<pre class="r"><code>library(formattable)
truck %&gt;% 
  select(TankMiles,Gallons,MPG,Location) %&gt;%
  group_by(Location) %&gt;%
  summarise_all(.funs = mean, na.rm = TRUE) %&gt;%
  mutate_if(is.numeric, round, 2) %&gt;%
  mutate(MPG = cell_spec(MPG, &quot;html&quot;, color = ifelse(MPG == max(MPG), &quot;red&quot;, ifelse(MPG== min(MPG), &quot;blue&quot;, &quot;black&quot;)))) %&gt;%
  mutate(TankMiles = cell_spec(TankMiles, &quot;html&quot;, color = ifelse(TankMiles == max(TankMiles), &quot;red&quot;, ifelse(TankMiles== min(TankMiles), &quot;blue&quot;, &quot;black&quot;)))) %&gt;%
  mutate(Gallons = cell_spec(Gallons, &quot;html&quot;, color = ifelse(Gallons == max(Gallons), &quot;red&quot;, ifelse(Gallons== min(Gallons), &quot;blue&quot;, &quot;black&quot;)))) %&gt;%
   kable(format = &quot;html&quot;, escape = F, align = &quot;l&quot;) %&gt;%
  kable_styling(&quot;striped&quot;, full_width = F)</code></pre>
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Location
</th>
<th style="text-align:left;">
TankMiles
</th>
<th style="text-align:left;">
Gallons
</th>
<th style="text-align:left;">
MPG
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Georgia
</td>
<td style="text-align:left;">
<span style="     color: black !important;">377.61</span>
</td>
<td style="text-align:left;">
<span style="     color: black !important;">21.81</span>
</td>
<td style="text-align:left;">
<span style="     color: red !important;">17.31</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Hawaii
</td>
<td style="text-align:left;">
<span style="     color: black !important;">430.06</span>
</td>
<td style="text-align:left;">
<span style="     color: black !important;">27.88</span>
</td>
<td style="text-align:left;">
<span style="     color: black !important;">15.43</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Missouri 1
</td>
<td style="text-align:left;">
<span style="     color: black !important;">387.49</span>
</td>
<td style="text-align:left;">
<span style="     color: black !important;">25.38</span>
</td>
<td style="text-align:left;">
<span style="     color: black !important;">15.34</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Missouri 2
</td>
<td style="text-align:left;">
<span style="     color: black !important;">344.99</span>
</td>
<td style="text-align:left;">
<span style="     color: black !important;">22.42</span>
</td>
<td style="text-align:left;">
<span style="     color: black !important;">15.51</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
New Mexico
</td>
<td style="text-align:left;">
<span style="     color: black !important;">374.48</span>
</td>
<td style="text-align:left;">
<span style="     color: black !important;">24</span>
</td>
<td style="text-align:left;">
<span style="     color: black !important;">15.55</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
New York 1
</td>
<td style="text-align:left;">
<span style="     color: black !important;">333.94</span>
</td>
<td style="text-align:left;">
<span style="     color: black !important;">20.7</span>
</td>
<td style="text-align:left;">
<span style="     color: black !important;">16.11</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
New York 2
</td>
<td style="text-align:left;">
<span style="     color: black !important;">372.16</span>
</td>
<td style="text-align:left;">
<span style="     color: black !important;">27.9</span>
</td>
<td style="text-align:left;">
<span style="     color: black !important;">13.12</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Ohio
</td>
<td style="text-align:left;">
<span style="     color: red !important;">444.93</span>
</td>
<td style="text-align:left;">
<span style="     color: red !important;">29.11</span>
</td>
<td style="text-align:left;">
<span style="     color: black !important;">15.22</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Texas
</td>
<td style="text-align:left;">
<span style="     color: blue !important;">317.75</span>
</td>
<td style="text-align:left;">
<span style="     color: blue !important;">19.2</span>
</td>
<td style="text-align:left;">
<span style="     color: black !important;">16.6</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Virginia
</td>
<td style="text-align:left;">
<span style="     color: black !important;">337.6</span>
</td>
<td style="text-align:left;">
<span style="     color: black !important;">24.9</span>
</td>
<td style="text-align:left;">
<span style="     color: blue !important;">11.02</span>
</td>
</tr>
</tbody>
</table>
<p>This chart shows highlights some interesting points.</p>
<ul>
<li><p>First, I did a ton of highway driving while I lived in Georgia to attain the best miles per gallon.</p></li>
<li><p>My top average miles per tank and average gallons per fill up were from Ohio. I would drive my truck till it was almost empty because I could get free 30 gallons of gasoline based off of money spent at our local grocery store.</p></li>
<li><p>The worse miles per gallon is Virginia. Well, since I only had two fill ups and they were both after I essentially killed the truck, this is no surprise.</p></li>
<li><p>The worse miles per tank and gallons per fill up were in Texas when my dad still possessed the truck (and doesn’t live as close to the edge as I do).</p></li>
</ul>
</div>
<div id="time-spent-in-each-location-ive-lived" class="section level3">
<h3>Time Spent in Each Location I’ve Lived</h3>
<p>How much time did I spend in each location? How many miles did I drive at each place?</p>
<pre class="r"><code>truck %&gt;% 
  group_by(Location) %&gt;%
  summarise(Arrive_Location = min(FillUpDate),
            Leave_Location = max(FillUpDate),
            MilesDriven = round(max(TotalMiles)-min(TotalMiles))) %&gt;%
  arrange(Arrive_Location) %&gt;%
  mutate(DaysInLocation = Leave_Location-Arrive_Location,
         MilesPerDay = round(MilesDriven/as.numeric(DaysInLocation))) %&gt;%
  DT::datatable(options = list(paging = FALSE))</code></pre>
<div id="htmlwidget-1" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-1">{"x":{"filter":"none","data":[["1","2","3","4","5","6","7","8","9","10"],["Texas","New York 1","Georgia","Missouri 1","Hawaii","Missouri 2","New Mexico","Ohio","New York 2","Virginia"],["2006-02-17","2006-03-10","2007-06-02","2007-08-04","2008-03-04","2011-09-30","2012-08-15","2014-08-09","2016-05-19","2019-07-12"],["2006-02-27","2007-05-31","2007-07-30","2008-01-08","2011-08-20","2012-08-09","2014-08-05","2016-05-08","2019-05-18","2019-07-19"],[905,7740,8052,5466,53314,19480,34110,23443,13228,401],[10,447,58,157,1264,314,720,638,1094,7],[90,17,139,35,42,62,47,37,12,57]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>Location<\/th>\n      <th>Arrive_Location<\/th>\n      <th>Leave_Location<\/th>\n      <th>MilesDriven<\/th>\n      <th>DaysInLocation<\/th>\n      <th>MilesPerDay<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"paging":false,"columnDefs":[{"className":"dt-right","targets":[4,6]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
<p>Interesting Notes:</p>
<ul>
<li>It appears, unsurprisingly, I spent the most time and drove the most miles in Hawaii. That’s lots of miles going around in circles.<br />
</li>
<li>What is surprising about Hawaii? I somehow managed 42 miles per day on the island. I put about 32 miles a day going to work and back, so I must have been doing some good weekend sightseeing. This even spans a 4 month deployment.<br />
</li>
<li>The most miles per day was spent in Georgia. I think I drove to Texas 3 times during my almost 2 months living there.<br />
</li>
<li>I clearly didn’t drive that much either time I was in NY. The first time was when I was a cadet. Those 21 miles per day even includes the transit to Georgia (with a pit stop in Texas), so I was doing a good job of studying instead of traveling.The second time was when I was a faculty member. Since my wife had the primary family vehicle, I’m still wondering how I achieved 12 miles per day.</li>
</ul>
<p>Lets look at this visually.</p>
<pre class="r"><code>truck %&gt;% 
  group_by(Location) %&gt;%
  summarise(Arrive_Location = min(FillUpDate),
            Leave_Location = max(FillUpDate),
            MilesDriven = round(max(TotalMiles)-min(TotalMiles))) %&gt;%
  arrange(Arrive_Location) %&gt;%
  mutate(DaysInLocation = Leave_Location-Arrive_Location,
         MilesPerDay = round(MilesDriven/as.numeric(DaysInLocation)),
         DaysInLocation = as.numeric(DaysInLocation)) %&gt;%
  gather(Attribute, Measurement, -Location, -Arrive_Location, -Leave_Location) %&gt;% 
  group_by(Attribute) %&gt;%
  mutate(order = rank(Measurement)) %&gt;% 
  # ggplot(aes(x=Location,y=Measurement)) +
  ggplot(aes(x=drlib::reorder_within(Location,-order,Measurement),y=Measurement)) +
  geom_col(aes(fill = Location)) +
  drlib::scale_x_reordered() +
  facet_wrap(~Attribute, scales = &quot;free&quot;) +
  labs(title = &quot;Miles Driven in Each Location&quot;, x = &quot;Location&quot;, y = &quot;Miles Driven&quot;) +
  coord_flip() +
  theme(legend.position = &quot;none&quot;, axis.text.x = element_text(angle = 45, hjust = 1))</code></pre>
<p><img src="https://www.dustysturner.com/post/a-farewell-ode-to-my-old-grey-truck/index_files/figure-html/unnamed-chunk-10-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>A picture (graph) is worth 1000 words.</p>
</div>
<div id="rate-of-miles-over-time" class="section level3">
<h3>Rate of Miles Over Time</h3>
<pre class="r"><code>truck %&gt;%
  ggplot(aes(x=FillUpDate,y=TotalMiles,color = Location) ) +
  geom_point() +
  geom_line() +
  scale_x_date(breaks = &quot;year&quot;,labels = scales::date_format(&quot;%Y&quot;)) +
  scale_y_continuous(labels = scales::comma) +
  labs(title = &quot;Miles Added Over Time&quot;, x = &quot;Fill Up Date&quot;, y = &quot;Total Miles&quot;)</code></pre>
<p><img src="https://www.dustysturner.com/post/a-farewell-ode-to-my-old-grey-truck/index_files/figure-html/unnamed-chunk-11-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>From this plot, you can see several take-aways:</p>
<ul>
<li>There was a time when I was really racking up the miles. Hawaii through Ohio was a prosperous time for the old truck. But if you notice, there’s a clear inflection point in Ohio where things start dropping off after we bought a new family car.</li>
<li>There is also a clear drop off in the rate of fill ups in NY.<br />
</li>
<li>There are also 4 periods of times with no fill ups. Two of them were on either side of Hawaii while my truck was getting shipped. The other two are both my deployments; with one fill up mid deployment while in New Mexico. Thanks Jill!</li>
</ul>
</div>
<div id="time-between-fill-ups" class="section level3">
<h3>Time Between Fill-ups</h3>
<p>How often did a tank of gas last?</p>
<pre class="r"><code>truck %&gt;%
  select(FillUpDate,FinishTankDate) %&gt;%
  mutate(DaysBetweenFillUps = FinishTankDate-FillUpDate) %&gt;%
  group_by(DaysBetweenFillUps)%&gt;%
  count() -&gt; FillUps

FillUps %&gt;%
  arrange(desc(n)) %&gt;%
  ungroup() %&gt;%
  top_n(5,n) %&gt;%
  kable() %&gt;%
  kable_styling(&quot;striped&quot;, full_width = F)</code></pre>
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
DaysBetweenFillUps
</th>
<th style="text-align:right;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
1 days
</td>
<td style="text-align:right;">
32
</td>
</tr>
<tr>
<td style="text-align:left;">
8 days
</td>
<td style="text-align:right;">
32
</td>
</tr>
<tr>
<td style="text-align:left;">
6 days
</td>
<td style="text-align:right;">
31
</td>
</tr>
<tr>
<td style="text-align:left;">
0 days
</td>
<td style="text-align:right;">
28
</td>
</tr>
<tr>
<td style="text-align:left;">
9 days
</td>
<td style="text-align:right;">
28
</td>
</tr>
</tbody>
</table>
<p>It appears the most often days between fill ups was a tie for both 1 day and 8 days.</p>
<p>Lets Visualize it:</p>
<pre class="r"><code>FillUps %&gt;%
  ggplot(aes(x=DaysBetweenFillUps,y=n)) +
  geom_col() +
  labs(x=&quot;Days Between Fill Ups&quot;, y=&quot;Number of Fill Ups&quot;, title = &quot;How Many Days Did a Tank of Gas Last?&quot;)</code></pre>
<p><img src="https://www.dustysturner.com/post/a-farewell-ode-to-my-old-grey-truck/index_files/figure-html/unnamed-chunk-13-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre class="r"><code>FillUps %&gt;%
  arrange(desc(DaysBetweenFillUps)) %&gt;%
  ungroup() %&gt;%
  top_n(5,DaysBetweenFillUps) %&gt;%
  kable() %&gt;%
  kable_styling(&quot;striped&quot;, full_width = F)</code></pre>
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
DaysBetweenFillUps
</th>
<th style="text-align:right;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
120 days
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
73 days
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
66 days
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
63 days
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
61 days
</td>
<td style="text-align:right;">
2
</td>
</tr>
</tbody>
</table>
<p>Also of note, the longest time between fill ups was 120 days. This must have been during one of my deployments.</p>
</div>
<div id="more-gas-on-certain-days" class="section level3">
<h3>More Gas on Certain Days?</h3>
<p>I also wonder if I happen to have filled up the tank more often on one day than another.</p>
<pre class="r"><code>truck %&gt;%
  mutate(Weekday = weekdays(FillUpDate)) %&gt;%
  select(TankMiles,Location,Weekday,FillUpDate) %&gt;%
  # select(-FillUpDate,-FinishTankDate) %&gt;%
  # gather(Measurement, Value, -Weekday, -Location) %&gt;%
  ggplot(aes(x=fct_relevel(Weekday, c(&quot;Sunday&quot;,&quot;Monday&quot;,&quot;Tuesday&quot;,&quot;Wednesday&quot;,&quot;Thursday&quot;)))) +
  geom_bar() +
  labs(x=&quot;Day of Week&quot;, y = &quot;Number of Fill-ups&quot;, title = &quot;What Day Did I Fill Up The Most?&quot;) +
  theme(legend.position = &quot;none&quot;, axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5))</code></pre>
<p><img src="https://www.dustysturner.com/post/a-farewell-ode-to-my-old-grey-truck/index_files/figure-html/unnamed-chunk-15-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The bar chart indicates that I might fill up more on Friday than any other day.</p>
<p>Lets look at a few statistical tests to see if <code>Weekday</code> impacts fill-ups.</p>
<pre class="r"><code>fisher =
  truck %&gt;%
  mutate(Weekday = weekdays(FillUpDate)) %&gt;%
  select(Weekday) %&gt;%
  count(Weekday, name = &quot;DaysFilledUp&quot;) %&gt;%
  left_join(
    tibble(
      date = seq(ymd(min(truck$FillUpDate)), ymd(max(truck$FillUpDate)), by = &#39;1 day&#39;)) %&gt;%
      mutate(Weekday = weekdays(date))  %&gt;%
      count(Weekday, name = &quot;Total&quot;)) %&gt;%
  mutate(DaysNotFilledUp = Total-DaysFilledUp) %&gt;%
  select(-Total)

fisher </code></pre>
<pre><code>## # A tibble: 7 x 3
##   Weekday   DaysFilledUp DaysNotFilledUp
##   &lt;chr&gt;            &lt;int&gt;           &lt;int&gt;
## 1 Friday              75             626
## 2 Monday              60             640
## 3 Saturday            66             634
## 4 Sunday              56             644
## 5 Thursday            62             638
## 6 Tuesday             59             641
## 7 Wednesday           54             646</code></pre>
<p>The table above shows how many times I filled up with gas on each day of the week and how many days I had the opportunity to fill up and did not. Essentially the question we are asking is: Is there something about Day of the Week which would impact whether or not I filled up with gas? Equivalently, is there something about filling up (or not) that impacts the day of the week? AKA: Are day of the week and fill ups independent?</p>
<p>Lets turn to several statistical tests.</p>
<p>If you are old school: The <span class="math inline">\(\chi^2\)</span> test.</p>
<pre class="r"><code>fisher %&gt;%
  select(-Weekday) %&gt;%
  chisq.test()</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  .
## X-squared = 5.2405, df = 6, p-value = 0.5134</code></pre>
<p>Since the null hypothesis is that there is no difference between day of week and fill up or not (also known as independence), the P Value is high so we ‘fail to reject’ this. We conclude that there’s no difference between day of week and decision to fill up or not. We could also say that the probability that they came from the same distribution is fairly high (.5134) therefore we do not have much evidence to say that they are different.</p>
<p>If you are new school, you turn to Fisher’s Exact Test. Essentially, if we lock in the amount of ‘fill ups’ over the time I owned the pick up and were to calculate every possible combination of days of which I could fill up with gas (eg., all on Monday, all but one on Monday and one on Tuesday, and so on), how extreme is what we saw. Fisher figured out that we could calculate that exact probability - and hence we have Fisher’s Exact Test.</p>
<pre class="r"><code>fisher %&gt;%
  select(-Weekday) %&gt;%
  fisher.test(workspace = 1000000)</code></pre>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data
## 
## data:  .
## p-value = 0.5311
## alternative hypothesis: two.sided</code></pre>
<p>It turns out that there is a 53.11% chance that we’d see what happened or see something more extreme by chance. I dare say that there is no relationship between day of week and the decision to fill up with gas.</p>
</div>
<div id="heat-map-of-fill-ups" class="section level3">
<h3>Heat-map of Fill Ups</h3>
<p>The map below shows dates in which I filled up my truck with gasoline. The darker green indicates more gallons – the lighter indicates fewer gallons. The dark dates mean I did not fill up with gasoline on that date.</p>
<pre class="r"><code>truck %&gt;%
  complete(FillUpDate = seq.Date(min(FillUpDate), max(FillUpDate), by=&quot;day&quot;)) %&gt;%
  mutate(monthweek = week(FillUpDate)) %&gt;%
  mutate(Weekday = weekdays(FillUpDate)) %&gt;%
  mutate(year = year(FillUpDate)) %&gt;%
  mutate(month = month(FillUpDate)) %&gt;% 
  group_by(month) %&gt;%
  mutate(monthweek = monthweek - min(monthweek)) %&gt;%
  ggplot(aes(y=monthweek,x=fct_relevel(Weekday, c(&quot;Sunday&quot;,&quot;Monday&quot;,&quot;Tuesday&quot;,&quot;Wednesday&quot;,&quot;Thursday&quot;)), fill = Gallons)) +
  geom_tile(color = &quot;white&quot;) +
  facet_grid(year~month, scales = &quot;free&quot;) +
  scale_fill_gradient(low=&quot;white&quot;, high=&quot;green&quot;, na.value = &quot;black&quot;) +  
  labs(x = &quot;Weekday&quot;, y = &quot;Week of Month&quot;, title = &quot;Time-Series Calendar Heat-map: Amount of Gas Pumped on Each Day&quot;, caption = &quot;Days with no gas are denoted in White&quot;) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = -0), axis.text.y = element_blank(), axis.ticks.y = element_blank()) </code></pre>
<p><img src="https://www.dustysturner.com/post/a-farewell-ode-to-my-old-grey-truck/index_files/figure-html/unnamed-chunk-19-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>I’ll admit, its hard to glean anything from this heat-map…. But I spent a lot of work creating it so I’m going to leave it.</p>
</div>
</div>
<div id="feedback-welcome" class="section level1">
<h1>Feedback welcome</h1>
<p>As always, I do this blog to learn new things, hopefully teach others from my experience, and hopefully receive (respectful and helpful) feedback.</p>
<p>Here’s a picture of old and new meeting!</p>
<center>
<img src="images/bothedit.jpg" alt="bothedit" width="400">
</center>
<p>Please leave your thoughts below!!</p>
</div>

          
          
          
        </div>
        
        

        

        

      </div>
    </section>

    
    <footer class="pt-8 max-w-prose print:hidden">
      
  
    
    
    
    <div class="pt-8">
      <hr class="border-dotted border-neutral-300 dark:border-neutral-600">
      <div class="flex justify-between pt-3">
        <span class="flex flex-col">
          
            <a
              class="flex text-neutral-700 hover:text-primary-600 dark:text-neutral dark:hover:text-primary-400"
              href="/post/fantasy-football-2019-analysis/">
              <span class="leading-6">
                <span class="inline-block rtl:rotate-180">&larr;</span>&ensp;Fantasy Football 2019 Analysis
              </span>
            </a>
            
              <span class="ms-6 mt-1 text-xs text-neutral-500 dark:text-neutral-400">
                <time datetime="2019-10-05T00:00:00&#43;00:00">5 October 2019</time>
              </span>
            
          
        </span>
        <span class="flex flex-col items-end">
          
            <a
              class="flex text-right text-neutral-700 hover:text-primary-600 dark:text-neutral dark:hover:text-primary-400"
              href="/post/wheel-spin-strategy-on-the-price-is-right/">
              <span class="leading-6">
                Wheel Spin Strategy On The Price Is Right&ensp;<span class="inline-block rtl:rotate-180">&rarr;</span>
              </span>
            </a>
            
              <span class="me-6 mt-1 text-xs text-neutral-500 dark:text-neutral-400">
                <time datetime="2020-08-01T00:00:00&#43;00:00">1 August 2020</time>
              </span>
            
          
        </span>
      </div>
    </div>
  


      
        
          
        
      
    </footer>
  </article>

        


  






<div
  id="scroll-to-top"
  class="fixed bottom-6 end-6 z-50 transform translate-y-4 opacity-0 duration-200">
  <a
    href="#the-top"
    class="pointer-events-auto flex h-12 w-12 items-center justify-center rounded-full bg-neutral/50 text-xl text-neutral-700 hover:text-primary-600 dark:bg-neutral-800/50 dark:text-neutral dark:hover:text-primary-400"
    aria-label="Scroll to top"
    title="Scroll to top">
    &uarr;
  </a>
</div>

      </main><footer id="site-footer" class="py-10 print:hidden">
  
  
    
  
  <div class="flex items-center justify-between">
    
    
      <p class="text-sm text-neutral-500 dark:text-neutral-400">
          &copy;
          2026
          Dusty Turner
      </p>
    

    
    
      <p class="text-xs text-neutral-500 dark:text-neutral-400">
        
        
        Powered by <a class="hover:underline hover:decoration-primary-400 hover:text-primary-500"
          href="https://gohugo.io/" target="_blank" rel="noopener noreferrer">Hugo</a> &amp; <a class="hover:underline hover:decoration-primary-400 hover:text-primary-500"
          href="https://blowfish.page/" target="_blank" rel="noopener noreferrer">Blowfish</a>
      </p>
    
  </div>
  
    <script>
      mediumZoom(document.querySelectorAll("img:not(.nozoom)"), {
        margin: 24,
        background: "rgba(0,0,0,0.5)",
        scrollOffset: 0,
      });
    </script>
  
  
  
</footer>
<div
  id="search-wrapper"
  class="invisible fixed inset-0 flex h-screen w-screen cursor-default flex-col bg-neutral-500/50 p-4 backdrop-blur-sm dark:bg-neutral-900/50 sm:p-6 md:p-[10vh] lg:p-[12vh] z-500"
  data-url="https://www.dustysturner.com/">
  <div
    id="search-modal"
    class="flex flex-col w-full max-w-3xl min-h-0 mx-auto border rounded-md shadow-lg top-20 border-neutral-200 bg-neutral dark:border-neutral-700 dark:bg-neutral-800">
    <header class="relative z-10 flex items-center justify-between flex-none px-2">
      <form class="flex items-center flex-auto min-w-0">
        <div class="flex items-center justify-center w-8 h-8 text-neutral-400">
          <span class="relative block icon"><svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="search" class="svg-inline--fa fa-search fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"/></svg>
</span>
        </div>
        <input
          type="search"
          id="search-query"
          class="flex flex-auto h-12 mx-1 bg-transparent appearance-none focus:outline-dotted focus:outline-2 focus:outline-transparent"
          placeholder="Search"
          tabindex="0">
      </form>
      <button
        id="close-search-button"
        class="flex items-center justify-center w-8 h-8 text-neutral-700 hover:text-primary-600 dark:text-neutral dark:hover:text-primary-400"
        title="Close (Esc)">
        <span class="relative block icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><path fill="currentColor" d="M310.6 361.4c12.5 12.5 12.5 32.75 0 45.25C304.4 412.9 296.2 416 288 416s-16.38-3.125-22.62-9.375L160 301.3L54.63 406.6C48.38 412.9 40.19 416 32 416S15.63 412.9 9.375 406.6c-12.5-12.5-12.5-32.75 0-45.25l105.4-105.4L9.375 150.6c-12.5-12.5-12.5-32.75 0-45.25s32.75-12.5 45.25 0L160 210.8l105.4-105.4c12.5-12.5 32.75-12.5 45.25 0s12.5 32.75 0 45.25l-105.4 105.4L310.6 361.4z"/></svg>
</span>
      </button>
    </header>
    <section class="flex-auto px-2 overflow-auto">
      <ul id="search-results">
        
      </ul>
    </section>
  </div>
</div>

    </div>
  </body>
  
</html>
